### ISSUE TITLE
Build error '_BitScanReverse64': identifier not found

### ISSUE THREAD

**Issue by ychding11** [mmp/pbrt-v3#100]
Hi 

I build code with vs2015 get lots of build errors about  _BitScanReverse64. I searched whole solution 
and found no definition.
```
pbrt-v3\src\core\pbrt.h(321): error C3861: '_BitScanReverse64': identifier not found
```

**Comment by mmp** [comment]
I believe this happens if you select a 32-bit built rather than a 64-bit
build in cmake. Can you double-check that?

(I'll add this to the FAQ over the weekend, since it's come up before.)

Thanks,
Matt

**Comment by ychding11** [comment]
I configure the project to X64 in vs2015. It still reports the same error.

**Comment by nejclesek** [comment]
Make sure you configure it in CMake; before you generate project files. Not manually in a VS solution.

**Comment by ychding11** [comment]
Hi @nejclesek ,

Use `cmake -G "Visual Studio 14 Win64" ..`  for vs2015.  Build passed, but lots of warnings.
Thanks!

**Comment by mmp** [comment]
And for the record, 2f73f777943d8dce328079153464cc77f605e7ed fixed this for 32-bit builds.
