### ISSUE TITLE
Log2 function is redundant

### ISSUE THREAD

**Issue by Jesse-Bakker** [mmp/pbrt-v3#102]
The Log2 function in pbrt.h is redundant, as there is a log2 function defined in cmath/math.h which does exactly the same.

**Comment by Jesse-Bakker** [comment]
My mistake, some compilers do not support it

**Comment by mmp** [comment]
Hm, which compilers? It does look like C++11 has a std::log2():
http://en.cppreference.com/w/cpp/numeric/math/log2

Thanks,
Matt
