### ISSUE TITLE
I'm confused at some codes

### ISSUE THREAD

**Issue by zq317157782** [mmp/pbrt-v3#106]
is
` BSDF::Sample_f(...){
 ...
 bool reflect = Dot(*wiWorld, ng) * Dot(woWorld, ng) > 0;
...
}`
can instead by 
` BSDF::Sample_f(...){
 ...
 bool reflect =wo.z*wi.z> 0;
...
}`

**Comment by mmp** [comment]
Actually, that's wouldn't work as desired. The key detail is that `wi` and `wo` are transformed to the local shading coordinate system, which is defined with respect to the shading normal. That test (for whether to use reflection or transmission BxDF components) is based on the *geometric* normal.

**Comment by zq317157782** [comment]
3Q~
