### ISSUE TITLE
git.pbrt.org seems to be down

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [mmp/pbrt-v3#107]
git clone git://git.pbrt.org/pbrt-v3-scenes fails, unable to connect to git.pbrt.org.

**Comment by mmp** [comment]
Sorry about that; the machine rebooted but the git stuff didn't start correctly. Should be fixed now!

**Comment by yhori-huawei** [comment]
I got the same situation right now. Could you please check the reason?

**Comment by yhori-bg** [comment]
I got the same situation. Could you please check the server available?

**Comment by mmp** [comment]
Out of curiosity, have you been able to connect to it successfully previously, or is this the first time you've tried?

I just checked and it seems to be up and working correctly (I did a test pull from it to my computer at home and that worked successfully.) FWIW the snapshot available at http://storage.googleapis.com/pbrt/pbrt-scenes.git.tar.gz is quite recent, as an alternative.

**Comment by amtinits** [comment]
The git server seems to be down again :(

**Comment by mmp** [comment]
Hm, "works for me". Can you run your git command with --verbose and post the error you're seeing?

**Comment by amtinits** [comment]
I've tried from servers on different networks, always the same result:
```
pbrt-v3-scenes$ git remote --verbose
origin  git://git.pbrt.org/pbrt-v3-scenes (fetch)
origin  git://git.pbrt.org/pbrt-v3-scenes (push)

pbrt-v3-scenes$ git fetch --verbose
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... fatal: unable to connect to git.pbrt.org:
git.pbrt.org[0: 146.148.96.151]: errno=Connection refused
```

**Comment by mmp** [comment]
Fixed now--sorry for the trouble!

**Comment by evil84** [comment]
The git server seems to be down again :(

**Comment by mmp** [comment]
I'm not sure what happened, but I rebooted it and restarted everything. It seems fine, but let me know if you're still seeing issues.

**Comment by kennyalive** [comment]
Git strikes again.

d:\codebases\pbrt>git clone git://git.pbrt.org/pbrt-v3-scenes --verbose
Cloning into 'pbrt-v3-scenes'...
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... fatal: unable to connect to git.pbrt.org:
git.pbrt.org[0: 146.148.96.151]: errno=Invalid argument

**Comment by mmp** [comment]
Sigh. I'm not sure what happened. It should be up again now. Sorry for any trouble.

**Comment by namedtoaster** [comment]
Looks to be down again. Seems to have been the last few times I've tried to grab it

**Comment by mmp** [comment]
Should be up again now. Apologies.

**Comment by rsburke4** [comment]
I think the server may be down again. Could you check this?

` git clone --verbose git://git.pbrt.org/pbrt-v3-scenes
Cloning into 'pbrt-v3-scenes'...
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... fatal: unable to connect to git.pbrt.org:
git.pbrt.org[0: 146.148.96.151]: errno=Connection refused
`

**Comment by mmp** [comment]
...and once again, it should be back up. Sorry for the trouble!
