### ISSUE TITLE
Houdini-exported volumes are invisible

### ISSUE THREAD

**Issue by crydalch** [mmp/pbrt-v3#117]
I'm working on a Houdini exporter to write volumes out for pbrt. When I render them, I don't see the volume in the rendered image, though the length of the render does seem to indicate it should be.

![sanity_volume](https://cloud.githubusercontent.com/assets/458856/23537721/1fc73654-ff9c-11e6-987d-a49b419ed1c5.png)

Here are the render statistics:

```
Statistics:
  BVH
    Interior nodes                                                      5
    Leaf nodes                                                          6
    Primitives per leaf node                            12 /            6 (2.00x)
  Integrator
    Camera rays traced                                          943718400
    Surface interactions                                       2831155200
    Path length                                                     0.000 avg [range 0.000000 - 0.000000]
  Intersections
    Regular ray intersection tests                             2831155200
    Ray-triangle intersection tests             1887436804 /   3774873716 (50.00%%)
  Memory
    BVH tree                                                         0.00 MiB
    Texture MIP maps                                               128.00 MiB
    Triangle meshes                                                  0.00 MiB
  Scene
    Shapes created                                                     12
    Triangles per triangle mesh                         12 /            1 (12.00x)
  Texture
    Texture map trilerp lookups                                 952107008
  Time
    BVH construction                                                0.000 s
    MIP map creation                                                0.089 s
    Rendering                                                     104.432 s
  Profile
    Integrator::Render()                                            99.28 %
      Camera::GenerateRay[Differential]()                            6.77 %
      Sampler::StartPixelSample()                                    6.59 %
      SamplerIntegrator::Li()                                       77.65 %
        Accelerator::Intersect()                                    47.28 %
          Triangle::Intersect()                                     27.17 %
        MIPMap::Lookup() (trilinear)                                 6.17 %
        Material::ComputeScatteringFunctions()                       0.10 %
    MIPMap::Lookup() (trilinear)                                     0.34 %
    Startup and scene construction                                   0.38 %

```

And attached is my scene files, which I'm rendering like this: `pbrt sanity_volume.pbrt`. I don't see any load errors or warnings when I run, it just starts rendering and completes fine, except for the render not having the volume.

Is there something wrong about the volume files themeselves, or something else I've overlooked with teh scene? Any suggestions would be great. Thanks

[sanity_volume.tar.gz](https://github.com/mmp/pbrt-v3/files/815787/sanity_volume.tar.gz)

**Comment by mmp** [comment]
First, I'm super excited about the idea of a Houdini -> pbrt exporter;
please don't hesitate to send along other questions / issues you run into
along the way. It'd be really great to get some great scenes via Houdini
for the scenes distribution.

It took me a while to track down what's going on (which suggests that there
are some usability issues with pbrt's volume support), but in the end, it
was very simple: pbrt assumes that the surface normals of geometry that
bounds a volume are pointing outside the volume's boundary, but it looks
like your PLY mesh has the normals pointing inside.  If you add a
"ReverseOrientation" before the ply mesh, things come out much better:

[image: Inline image 1]

(That was with the camera moved back a bit.) It does look like there's an
issue with indexing/ordering of the volume density values, but presumably
that'll be easy to chase down.

Note that I rendered that image with 16 samples per pixel--reducing your
number of pixel samples may be helpful for quick tests.

Finally, as a heads up: at one point I thought the issue might have been
that the camera was inside the bounds of the volume. If that is the case,
you'll want to specify the named medium before WorldBegin and also specify
a MediumInterface before you specify the camera, so that the camera knows
that its rays are starting out in the volume.

**Comment by crydalch** [comment]
Ah, interesting I never would have thought the mesh was reversed, but that worked, thanks for noticing it! I'm seeing the index/ordering issue you mentioned (your image didn't come through unfortunately, but I'm guessing it was similar to this):

![screenshot-window-2017-03-03-205658](https://cloud.githubusercontent.com/assets/458856/23575009/2a23ff16-0054-11e7-9386-67a49c748a2e.png)

What is the proper order for voxel indices? I should have guessed it wouldn't just work on the first try, but so far I haven't been able to crack it. Out of curiosity, what are the chances OpenVDB would end up in pbrt?

Thanks for the encouragement!

**Comment by crydalch** [comment]
Thanks for all the help Matt, I appreciate it. Re OpenVDB: The biggest benefit would be it'd be easy to get volumes from Houdini or other packages into pbrt, but you're right it's got a long list of dependencies. pbrt-tools is an interesting idea, as it's awesome that pbrt is very easy to build.

Okay, I'm pretty sure I've got the voxels in the correct order, though maybe I'm missing something when I write them to disk? Looking at the cloud/density_render.70.pbrt example file, each row of density values is 100, which corresponds to 'nx' (xres) right?  And when explaining the voxel layout, did you mean (0,1,zres-1), rather than (0,1,xres-1)? (I assumed that was just a typo). I'm trying to recreate this pattern in Houdini, to see if I can't figure out how to get rid of it that way.

Also I've been prototyping with numpy inside of Houdini, to write the data to disk, but maybe that's the problem:

```
h = """MakeNamedMedium "smoke" "string type" "heterogeneous" "integer nx" 89 "integer ny" 106 "integer nz" 82
        "point p0" [ -0.48 -0.5 -0.41 ] "point p1" [0.41 0.56 0.41 ]
        "float density" ["""
f = "]"
densities = np.frombuffer(geo.pointFloatAttribValuesAsString("density"), dtype="f4").copy()
d = np.reshape(densities, (densities.size/89, 89)) # Use volume xres instead of 65
np.savetxt('/tmp/mysmoke.pbrt', d, header=h, footer=f, fmt='%1.6f', comments='')
```

![volume_incorrect](https://cloud.githubusercontent.com/assets/458856/23690050/ba89cb68-038c-11e7-82ca-689b61b11a6e.png)

**Comment by mmp** [comment]
Sorry, I did miswrite it. I don't know how Houdini lays things out and don't know numpy, but the order should be something like:

```
for z = 0 to zres
  for y = 0 to yres
    for x  = 0 to xres
        print density value at (x, y, z)
```

**Comment by crydalch** [comment]
Finally, success! 

![screenshot-area-2017-03-31-000341](https://cloud.githubusercontent.com/assets/458856/24536257/320218ae-15a7-11e7-9caa-2b20bdc57c05.png)

It's pretty crude, but it's a start. Unfortunately in it's current state it requires an Education license of Houdini. I'll figure out how to expand it to more Houdini users. I've got it on my fork of pbrtv3 (I'll happily merge when it's in a somewhat better state): [https://github.com/crydalch/pbrt-v3/tree/houdini-volumes/exporters/houdini](https://github.com/crydalch/pbrt-v3/tree/houdini-volumes/exporters/houdini )

![screenshot-area-2017-03-31-000031](https://cloud.githubusercontent.com/assets/458856/24536307/8972d0b0-15a7-11e7-8d62-07a6bf1519df.png)

Thanks for the help Matt, I'm sure I'll be pinging you more in the future! :smile:

**Comment by mmp** [comment]
Hey, fantastic! Looking forward to it being ready for merging! Also, if you
are able to export some nice looking volumes, it'd be great to add them to
the scenes distribution / have them up on the gallery.

Thanks,
Matt

**Comment by crydalch** [comment]
Will do thanks!

**Comment by lwkobe** [comment]
@crydalch  Hi could you send you new sanity_volume.tar.gz ? I am using the pbrt to render my simulated data. But i don't know to write the scene file ? Could you give me some advice ? Thank you !

**Comment by crydalch** [comment]
@lwkobe Hey, there's a working example on #125 you can look at. Currently the "exporter" only writes out the ply bounding box and the volume to pbrt. The scene itself is still put together by hand unfortunately. 

My goal by the end of the month is to have  cameras, lights, and volumes working.

Hope that helps!

**Comment by mmp** [comment]
As a heads up, I've started hacking on this myself starting from @crydalch's code. First victory: getting the camera transform to work. :-). I'll continue working on this and see how far I can get.

**Comment by crydalch** [comment]
That's great Matt! Sorry I haven't had much to contribute recently on this front, thanks for taking a crack at it!

**Comment by crydalch** [comment]
FYI for anyone loooking here for part-Houdini integration, try this one: https://github.com/shadeops/houdini-pbrt-v3

(I haven’t tried it yet, but looks pretty comprehensive)
