### ISSUE TITLE
Hair material appears to have an importance sampling issue.

### ISSUE THREAD

**Issue by etheory** [mmp/pbrt-v3#121]
From what I can see, the hair works as follows.

With respect to the longitudinal roughness function:
1.) The theta_o is reflected to produce the required theta_i angle.
2.) This implies that the cuticle is effectively tilting the reflected lobe itself up or down. Since we are reflecting theta_o to produce some theta_r.
Hence theta_r, which is the reflected lobe direction, is theta_r = -theta_o + cuticleAngle
3.) Sampling this lobe must therefore be done by sampling theta_r. If we instead sample -theta_o, and then rotate the resulting angles, we'll get a mismatch between the sampling function and the current pdf evaluation for large cuticle angles.

As this is also effecting my own current implementation of a more advanced version of a similar shader I'm fairly sure this observation is accurate.

The fix would be to modify the shader to rotate theta_o, and not theta_i, both in Sample_f (sample the rotated angle, not rotate the sampled angle) and f.

**Comment by Immocat** [comment]
Hi @etheory,

Although it is one year after your post, I find the same problem here recently when exploring the hair shading. I think that pbrt's implementation is not the same as [Importance Sampling for Physically-based Hair Fiber Models] (http://cg.ibds.kit.edu/publications/pubhanika/2013_hairbrief.pdf) when importance sampling the longitudinal M function, which I think it is a bug as you mentioned. Also, I think your advice is basically correct. I also found some problem(maybe) when pbrt's code handling the numerical stability, which is not mentioned in hair chapter. I would like to do more implementation and test, and then write a report for @mmp as soon as possible. 

Zejian Wang (@Immocat)

**Comment by mmp** [comment]
Fixed now. Thanks to @rgirish28 for the PR, and many thanks to @Immocat and @etheory for the thorough explanations of the underlying error and the appropriate solution.

**Comment by etheory** [comment]
I know it's a few months ago now, but I've only just seen this. Thanks for finally getting around to it! Really appreciate it. Happy it's resolved now.

**Comment by Immocat** [comment]
Actually It's been a long time and I totally forget the details :laughing: . Looking forward to pbrt 4 now.
