### ISSUE TITLE
Defining Volume bounds with trimesh shape instead of ply

### ISSUE THREAD

**Issue by crydalch** [mmp/pbrt-v3#125]
For the Houdini exporter, it would simplify things if the volume's shape (bounds) could be defined directly in the pbrt scene via trimesh, instead of referencing an external ply file. When trying this route, however, the volume doesn't render the same as when using the ply shape. Is there something in pbrt that prohibits this, or did I mess up some of the formatting?

![pbrt_vol_trimesh_render_comparison](https://cloud.githubusercontent.com/assets/458856/24832525/0fe62528-1c80-11e7-8967-98e4a237b6ca.png)

Attached are the scene files and Houdini-exported volume test; `exporter_test.pbrt` references the included ply, and `exporter_test_alt.pbrt` uses the trimesh shape.

Thanks!

[hou_vol_export.tar.gz](https://github.com/mmp/pbrt-v3/files/907808/hou_vol_export.tar.gz)

**Comment by mmp** [comment]
It should just work. Make sure that the triangle orientations are consistent / correct and that they do in fact give a closed bounding box.

**Comment by crydalch** [comment]
Ah dang it, another mistake on my end. I was treating the integer index list as point numbers on the mesh, not indices into the positions list.

It works great now; this should simplify things significantly. Thanks @mmp
