### ISSUE TITLE
Compilation under Cygwin

### ISSUE THREAD

**Issue by tsulej** [mmp/pbrt-v3#127]
There are two problems when you try to compile under Cygwin.

First is connected to external glog lib, in the files src/ext/glog/src/utilities.cc, line 269
and src/ext/glog/src/googletest.h, lines: 524 and 557

`#elif defined OS_WINDOWS || defined OS_CYGWIN`
or
`#if defined OS_WINDOWS || defined OS_CYGWIN`

should be changed to:
`#elif defined OS_WINDOWS && !defined OS_CYGWIN`
or
`#if defined OS_WINDOWS && !defined OS_CYGWIN`
see: https://github.com/google/glog/pull/157

I'm aware that it's has nothing to do with pbrt itself, but I leave it for reference.

Second one is related to the fact that Cygwin doesn't have ITIMER_PROF implemented and app crashes.
To fix this just replace every occurrence of:
`#ifndef PBRT_IS_WINDOWS`
with
`#if !defined(PBRT_IS_WINDOWS) && !defined(__CYGWIN__)`
in src/core/stats.cpp

**Comment by mmp** [comment]
Thanks! Fixed on the pbrt side (I think--let me know if the change didn't take care of it.)

**Comment by tsulej** [comment]
Fixed - confirmed. Thank you!
