### ISSUE TITLE
Crown scene with wrong reflections/transmissions

### ISSUE THREAD

**Issue by jonasdeyson** [mmp/pbrt-v3#129]
The crown scene from the `git://git.pbrt.org/pbrt-v3-scenes` repository has a `Scale -1 1 1` inside the `WorldBegin` block. This causes wrong results with glass materials (e.g the gems on the crown). The scale should be moved to the beginning of the file.

Here're [the results](http://imgur.com/a/ci9Yy) before and after the fix.

**Comment by mmp** [comment]
Wow, great find!

I will push an update to the scenes repository after re-rendering the example images.

Thanks!!

**Comment by mmp** [comment]
Scene repository updated. Thanks again!
