### ISSUE TITLE
Build with visual studio 2017 on windows

### ISSUE THREAD

**Issue by shizumik** [mmp/pbrt-v3#133]
I'm sorry to trouble but I am working to solve my problem for two days. I can't locate where occurs the question.  I do follow the steps below:
    1.download the pbrt-v3 code
    2.open the folder in vs2017
    3.Cmake - Build All ( x64 Debug,and I've decomment that #defind ...)
    4.Then i can go into the directory that the VS generates. This is the path: C:\Users\SHIZU-NOTEBOOK\AppData\Local\CMakeBuild\09de91a8-9231-7c30-bdbd-0716ebaaee5d\build\x64-Debug
    5.Here are pbrt.exe, pbrt_test.exe and so on. It is said that there is a bin and set PBRT_SEARCHPATH, But i can't find xxx/bin anywhere.
Did I build in a wrong way or failed to build the code? 
Thank you very much!

**Comment by shizumik** [comment]
I'v solved it by myself now. It is really a foolish problem that i didn't set path right. And the pbrt is so cool!!

**Comment by CLonely** [comment]
Hi! I recently attempt to build pbrt-v3 on my windows but when I use cmake to build VS2017 solution, a problem accurred, and I don't know how to solve it. Please lend a little help, thanks!
![1](https://user-images.githubusercontent.com/29160852/30727251-c2bb2484-9f82-11e7-896b-ccb8a2a20fa6.PNG)

**Comment by sriravic** [comment]
You have not cloned the repo with the required libraries. It clearly indicates that in the CMake error message. 

Go to the directory containing the repo and type "git submodule update --init --recursive". This will download the external libraries required. You should be able to build pbrt then.

**Comment by CLonely** [comment]
@sriravic Hi, thanks for answering! Saddly I'm not a computer science major student, so there are lots of things I don't understand like where to run the git submodule command or which directory should I go to. I just want to learn some techniques of computer graphics. If you can give a step by step instruction, I will definitely appreciate it. Thanks a lot!
