### ISSUE TITLE
pbrt-v3-scenes/landscape/f6-17.pbrt does not render

### ISSUE THREAD

**Issue by nohtanoj** [mmp/pbrt-v3#134]
Hi,

I tried rendering the "f6-17.pbrt" file in the landscapes directory inside pbrt-v3-scenes, but all I'm getting is a pattern that looks like brown noise, which is completely wrong.

I'm running "./pbrt pbrt-v3-scenes/landscape/f6-17.pbrt"

Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/11449229/26119709/01aa0fd6-3a23-11e7-9756-19e1d5446642.png)

Thanks

**Comment by mmp** [comment]
Hm, interesting. I'm seeing that as well. I'll dig into it!

**Comment by nohtanoj** [comment]
Great! Also, if this helps, I get a similar issue when trying to replace the perspective camera with a realistic camera inside simple/dof-dragons.pbrt (white noise instead of brown noise), so I think this problem might be somehow related to the realistic camera.
