### ISSUE TITLE
pbrt-v3-scenes/sanmiguel/f6-17.pbrt does not render?

### ISSUE THREAD

**Issue by nohtanoj** [mmp/pbrt-v3#135]
When running:

./pbrt ~/dir/pbrt-v3-scenes/sanmiguel/f6-17.pbrt

I get the following error:

pbrt version 3 (built May 18 2017 at 15:07:07) [Detected 8 cores]
Copyright (c)1998-2016 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
The source code to pbrt (but *not* the book contents) is covered by the BSD License.
See the file LICENSE.txt for the conditions of the license.
E0519 13:23:32.865339 2044002304 error.cpp:89] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/sanmiguel-geom.pbrt(722): Named material "Sun_Light" not defined. Using "matte".
E0519 13:23:33.841183 2044002304 error.cpp:89] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/sanmiguel-geom.pbrt(17043): Named material "Fill_Light_Patio" not defined. Using "matte".
W0519 13:23:46.386222 2044002304 error.cpp:87] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/enredadera-mat.pbrt(34): Named material "Tronco" redefined.
W0519 13:23:51.520692 2044002304 error.cpp:87] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/plantas-mat.pbrt(1364): Texture "Map #25" being redefined
W0519 13:23:51.584584 2044002304 error.cpp:87] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/plantas-mat.pbrt(1387): Texture "Map #26" being redefined
W0519 13:23:52.176950 2044002304 error.cpp:87] ~/dir/pbrt-v3-scenes/sanmiguel/geometry/plantas-mat.pbrt(2192): Texture "Map #13" being redefined
F0519 13:24:02.063671 2044002304 realistic.cpp:456] Check failed: c > 0 (-0.00348178 vs. 0) Coefficient must be positive. It looks focusDistance: 0.55 is too short for a given lenses configuration
*** Check failure stack trace: ***
    @        0x10e287be1  google::LogMessage::Flush()
    @        0x10e28bb23  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e288579  google::LogMessageFatal::~LogMessageFatal()
    @        0x10e18f1cc  pbrt::RealisticCamera::FocusThickLens()
    @        0x10e18ec78  pbrt::RealisticCamera::FocusBinarySearch()
    @        0x10e18e8c5  pbrt::RealisticCamera::RealisticCamera()
    @        0x10e193284  pbrt::CreateRealisticCamera()
    @        0x10e068a4c  pbrt::MakeCamera()
    @        0x10e06f472  pbrt::RenderOptions::MakeCamera()
    @        0x10e06eb2c  pbrt::RenderOptions::MakeIntegrator()
    @        0x10e06e440  pbrt::pbrtWorldEnd()
    @        0x10e060a26  yyparse()
    @        0x10e12e332  pbrt::ParseFile()
    @        0x10e05e7b8  main
Abort trap: 6

Also, is the nomenclature for this file correct? I think this file f6-17.pbrt is supposed to correspond to Chapter 6, Figure 17 in the PBRT textbook, but there's also a file pbrt-v3-scenes/landscape/f6-17.pbrt, which doesn't seem to look like Chapter 6, Figure 17 in the PBRT textbook. Thanks!

**Comment by mmp** [comment]
Now fixed. Sorry for the trouble! (You're right that it's misnamed.)

**Comment by william-lawvere** [comment]
Thanks! Maybe it's a good idea to update the pbrt-v3-scenes repository with the right file name for "pbrt-v3-scenes/landscape/f6-17.pbrt" as well.

**Comment by nohtanoj** [comment]
Thanks! Maybe it's a good idea to update the name of "pbrt-v3-scenes/landscape/f6-17.pbrt" in the pbrt-v3 repository as well.

**Comment by mmp** [comment]
I've removed that file from the scenes repository, since I believe it's unused--presumably it was an earlier version of figure 6.17 that was later replaced with that San Miguel image.

Thanks again!
