### ISSUE TITLE
Is TransformCache actually used?

### ISSUE THREAD

**Issue by Narann** [mmp/pbrt-v3#153]
Hello!

First: Thanks for this wonderful book!

I'm reading the 3rd edition. The Transform chapter talk about TransformCache. But [a tiny search](https://github.com/mmp/pbrt-v3/search?utf8=%E2%9C%93&q=TransformCache&type=) indicate the class is not use at all.

Maybe a leftover?

Keep the good work! :)

**Comment by mmp** [comment]
(Glad you've enjoyed the book!)

You search seems to be incomplete (not sure why):

https://github.com/mmp/pbrt-v3/blob/b57b56cadd2e11ab3ad5d79b404234ca8b3871d9/src/core/api.cpp#L243

https://github.com/mmp/pbrt-v3/blob/b57b56cadd2e11ab3ad5d79b404234ca8b3871d9/src/core/api.cpp#L663

**Comment by Narann** [comment]
Thanks! I shouldn't have relied on Github search. I will search more carefully next time.

Keep the good work! :)
