### ISSUE TITLE
Disk shape position partial derivative

### ISSUE THREAD

**Issue by ksmolenskiy** [mmp/pbrt-v3#154]
Hello! Shouldn't disk dp/dv (disk.cpp line 79) be
`Vector3f dpdv = Vector3f(pHit.x, pHit.y, 0.) * (radius - innerRadius) / rHit;`
instead of 
`Vector3f dpdv = Vector3f(pHit.x, pHit.y, 0.) * (innerRadius - radius) / rHit;`
??

https://www.wolframalpha.com/input/?i=d%2Fdv+((1+-+v)+*+r0+%2B+v+*+r1)+*+cos(phi)

**Comment by mmp** [comment]
You are correct. Thanks for reporting this!
