### ISSUE TITLE
Question about HomogeneousMedium::Sample implementation

### ISSUE THREAD

**Issue by Immocat** [mmp/pbrt-v3#159]
I'm a little bit confused by the implementation of `HomogeneousMedium::Sample`.

Around line 57, `homogeneous.cpp`(Also at Page 894 in pbrt3 book)
```c++
Float dist = -std::log(1 - sampler.Get1D()) / sigma_t[channel];
Float t = std::min(dist * ray.d.Length(), ray.tMax);
```
As far as I know, the `dist` is the sampled distance over [0,+inf). For rays ( o + **d** * t ), `dist == t * ray.d.Length()`, and `t = dist / ray.d.Length()`.

Why the code is `dist * ray.d.Length()`? Maybe I misunderstand something, or it is a bug here.

**Comment by mmp** [comment]
Thanks!
