### ISSUE TITLE
I'm confused at some codes,again.

### ISSUE THREAD

**Issue by zq317157782** [mmp/pbrt-v3#170]
I'm reading the VolPathIntegrator and around line 79:
`if (ray.medium) beta *= ray.medium->Sample(ray, sampler, arena, &mi);`
but I found there is no **PhaseFunc**'s value and it's **PDF** here ,is it implicitly included here?Just because  **PhaseFunc** div **PDF** equals one?
I'm confused at here.
Thanks.

**Comment by Immocat** [comment]
I think there is no problem with the code. I suggest going into the details on page 891-894 and also page 901-903, pbrt v3.

When a ray hits a surface and the ray is in a medium, we need to sample a MediumInteraction. In medium->Sample, we only account for sample the distance. If we successfully sample a MediumInteraction(mi.IsValid() is true), the direct illumination, including phase function and pdf, are handled mainly by UniformSampleOneLight() in <Handle scattering at point in medium for volumetric path tracer> at page 902, pbrt v3.

**Comment by zq317157782** [comment]
Thanks！
