### ISSUE TITLE
splitdepth integer in CreateCurveShape(...)

### ISSUE THREAD

**Issue by wahn** [mmp/pbrt-v3#171]
Shouldn't the **line 475** in `src/shapes/curve.cpp` be **changed** from:

```c++
int sd = params.FindOneFloat("splitdepth", 3);
```

to:

```c++
int sd = params.FindOneInt("splitdepth", 3);
```

In the [documentation](http://www.pbrt.org/fileformat-v3.html#shapes) it says `splitdepth` has `integer` type, so it should be read by the matching function `FindOneInt(...)` in my opinion ...

**Comment by mmp** [comment]
Nice find--thanks! Fixed now.
