### ISSUE TITLE
Problem about "Sw" normalization in DisneyBSSRDF

### ISSUE THREAD

**Issue by Immocat** [mmp/pbrt-v3#173]
Hi,

The problem is described as following:

### PBD
The Separable BSSRDF is calculated by the equation before [11.7] on page 694 of pbrt v3 book. As the described in the last comment by @wjakob in issue #19, PBD tabulates the fresnel-scaled irradiance and the Fresnel term in "Sw" is to modulate the directional profile.

### DisneyBSSRDF
However, as mentioned in [[2015 Siggraph Course note](http://blog.selfshadow.com/publications/s2015-shading-course/burley/s2015_pbs_disney_bsdf_notes.pdf)](equation (5) and (6) on page 7) and [[Pixar Memo](http://graphics.pixar.com/library/ApproxBSSRDF/paper.pdf)], their profile is intrinsically normalized(Integrating `Rd` over hemisphere and area gets 1). 

### My thoughts:
So I think there should not be a `c` in "Sw" when DisneyBSSRDF is used. We only multiply two Fresnels, diffusion profile, and 1/pi. (As equation (5) in [[Jensen01](https://graphics.stanford.edu/papers/bssrdf/bssrdf.pdf)]). I am not sure if I am correct since there is a `C` in [[Pixar Memo](http://graphics.pixar.com/library/ApproxBSSRDF/paper.pdf)] without explanation. 

Thanks for your attention.

Zejian Wang

**Comment by mmp** [comment]
Nice find. I believe you're right. Fixed!
