### ISSUE TITLE
"Integrator/Path Length" stat declared as float in VolPathIntegrator

### ISSUE THREAD

**Issue by abusch** [mmp/pbrt-v3#176]
It's probably super minor, but for some reason, the "Integrator/Path Length" stat in `VolPathIntegrator` is declared as `STAT_FLOAT_DISTRIBUTION`, whereas it is declared as `STAT_INT_DISTRIBUTION` in `PathIntegrator`.

**Comment by mmp** [comment]
Thanks! Fixed.
