### ISSUE TITLE
BDPT and volpath integrators give different results

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v3#179]
With the attached scene, the BDPT and volpath integrators give significantly different results: the image is 12% brighter overall with volpath; this can be easily seen in the floor area, for example.

One possible clue is that this doesn't reproduce with a point light; they match (on average) in that case.

[bug.pbrt.txt](https://github.com/mmp/pbrt-v3/files/1858268/bug.pbrt.txt)

BDPT:
![bdpt](https://user-images.githubusercontent.com/102567/38064180-8c5375c8-32b1-11e8-9122-e9f3e70b958d.png)

Volpath:
![volpath](https://user-images.githubusercontent.com/102567/38064186-9040f80e-32b1-11e8-929e-c61efa46541d.png)

Diff image:
![diff](https://user-images.githubusercontent.com/102567/38064196-93b30946-32b1-11e8-9e5a-eba430118721.png)

**Comment by wjakob** [comment]
I can take a look at this, but it may take me a bit too get to it. One useful bit for debugging would be the image pyramid that can be dumped out with a separate debug flag. I suspect that one of the strategies may be losing track of the fact that we're inside a medium. (potentially related: I noticed that one "MediumInterface" line in the PBRT file is commented out).

**Comment by mmp** [comment]
If you can dig in at some point, that'd be fantastic. A few notes from some more digging here:

- I was suspicious of the fact that SpotLight::Sample_Le() sets the ray's medium to mediumInterface.inside (rather than .outside), but it turns out that only a Medium * is passed when creating the spotlight, which it stores (confusingly) in a MediumInterface that holds the same pointer for both inside and outside. It's probably worth switching this to .outside, for clarity, but doesn't affect the images.

- I tried to audit the BDPT code with this bug in mind to see if anything jumped out at me, but there wasn't anything immediately obvious.

Here's the image pyramid:
(s=0 are all black since it's a spot light)

s=1, t=2:
![bdpt_d01_s01_t02](https://user-images.githubusercontent.com/102567/38095074-657ca08c-3324-11e8-95f8-5d342eef9bbc.png)

s=2, t=1:
![bdpt_d01_s02_t01](https://user-images.githubusercontent.com/102567/38095084-6d3f2e84-3324-11e8-90f2-480e3b9f5e75.png)

s=1, t=3:
![bdpt_d02_s01_t03](https://user-images.githubusercontent.com/102567/38095172-9eff84a0-3324-11e8-87db-ee07d78b75c7.png)

s=2, t=2:
![bdpt_d02_s02_t02](https://user-images.githubusercontent.com/102567/38095247-d54ebe4a-3324-11e8-91fd-27c7dbe2c521.png)

s=3, t=1:
![bdpt_d02_s03_t01](https://user-images.githubusercontent.com/102567/38095254-dae166f0-3324-11e8-94da-48fd8eb53efe.png)

**Comment by mmp** [comment]
(Regarding that commented out MediumInterface; that has no effect, with or without it. Just a debugging experiment. I've confirmed that the rays generated by SpotLight::Sample_Le() do carry the right Medium in either case.)

**Comment by iliyang** [comment]
I'm experiencing a similar issue, with even more severe differences between the `volpath` and `bdpt` integrators:

**Area light source:** `volpath` (left) and `bdpt` (right):
![depth4_cornell_volpath](https://user-images.githubusercontent.com/802594/56155398-b4951f80-5fb2-11e9-9045-f645e3186fe1.png) ![depth4_cornell_bdpt](https://user-images.githubusercontent.com/802594/56155397-b3fc8900-5fb2-11e9-904e-d4bd49573c9c.png)

**Point light source:** `volpath` (left) and `bdpt` (right):
![depth4_pointlight_volpath](https://user-images.githubusercontent.com/802594/56156167-903a4280-5fb4-11e9-9049-02a40652c4f5.png) ![depth4_pointlight_bdpt](https://user-images.githubusercontent.com/802594/56156149-83b5ea00-5fb4-11e9-8a41-1787cea98c37.png)

ZIP file with the two variants of the scene:
[bdpt_heterogeneous_bug.zip](https://github.com/mmp/pbrt-v3/files/3081579/bdpt_heterogeneous_bug.zip)

I tried on a few of other scenes. For example, the `smoke-plume` (084 variant) scene interestingly produces the same image with `volpath` and `bdpt`. But when I switch to a point light source, `bdpt` goes bananas. It seems to me that the single scattering is not handled correctly?

**Comment by iliyang** [comment]
I dug a bit deeper, using the `visualizestrategies` and `visualizeweights` BDPT integrator options to generate images for the individual techniques for the point-light version of the scene. Looks like something's wrong with the camera connection technique.

`visualizestrategies = true` | -
------------ | -------------
bdpt_d00_s00_t02 | bdpt_d01_s00_t03
![bdpt_d00_s00_t02](https://user-images.githubusercontent.com/802594/56169424-f71c2380-5fd5-11e9-98dd-df7096fe92bf.png) | ![bdpt_d01_s00_t03](https://user-images.githubusercontent.com/802594/56169425-f71c2380-5fd5-11e9-802a-d84e4585d040.png)
bdpt_d01_s01_t02 | bdpt_d01_s02_t01
![bdpt_d01_s01_t02](https://user-images.githubusercontent.com/802594/56169426-f71c2380-5fd5-11e9-9f2b-70b5de6ed970.png) | ![bdpt_d01_s02_t01](https://user-images.githubusercontent.com/802594/56169427-f7b4ba00-5fd5-11e9-8c9d-8d632902c6fc.png)

Note that the bdpt_d01_s01_t02 technique alone produces the correct image (compare it with the maxdepth=1 `volpath` image above).

The weight images are similar:

`visualizeweights = true` | -
------------ | -------------
bdpt_d00_s00_t02 | bdpt_d01_s00_t03
![bdpt_d00_s00_t02](https://user-images.githubusercontent.com/802594/56169668-d1434e80-5fd6-11e9-87d9-f6117cc3dbc1.png) | ![bdpt_d01_s00_t03](https://user-images.githubusercontent.com/802594/56169669-d1dbe500-5fd6-11e9-846c-143380bade6e.png)
bdpt_d01_s01_t02 | bdpt_d01_s02_t01
![bdpt_d01_s01_t02](https://user-images.githubusercontent.com/802594/56169670-d1dbe500-5fd6-11e9-9315-961ccd576db9.png) | ![bdpt_d01_s02_t01](https://user-images.githubusercontent.com/802594/56169671-d1dbe500-5fd6-11e9-9452-09a9293ff76d.png)

**Comment by wjakob** [comment]
Just for the record: the issues that Iliyan Georgiev reported (now deleted) were due to an incorrect labeling of medium transitions in the scene.
