### ISSUE TITLE
AreaLight regression after issue #154

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v3#183]
Hello,

I notice an odd issue when using disk based AreaLightSources. While the light samples are taken from the correct side of the surface, the computed emitted light from when rays hit the light source is incorrect.  (DiffuseAreaLight::L(...) evaluates on the wrong side of the surface.)  I believe this is due to calculation of the geometry normal using the dpdu and dpdv within the SurfaceInteraction class. Prior to #154, the cross product of dpdu and dpdv would result in a geometric normal in the +z axis, now its resulting in a geometric normal in the -z axis.

**Pre #154**
![pre_154](https://user-images.githubusercontent.com/2104033/38954271-372b95de-431f-11e8-9eab-897311310f2c.jpg)

**Post #154**
![post_154](https://user-images.githubusercontent.com/2104033/38954275-3c56a17a-431f-11e8-81de-fab21b16f9c0.jpg)

[disk.pbrt.gz](https://github.com/mmp/pbrt-v3/files/1925588/disk.pbrt.gz)

Thanks!

**Comment by mmp** [comment]
Fixed by 2f0852c; closing this out now.
