### ISSUE TITLE
doxygen problem when build

### ISSUE THREAD

**Issue by miccall** [mmp/pbrt-v3#185]
Found Doxygen: D:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.13") found components:  doxygen missing components:  dot

Could you help me ？ 

![image](https://user-images.githubusercontent.com/20721387/39248076-bbbf54ee-48cd-11e8-8810-edbf60ff62be.png)

**Comment by mmp** [comment]
That shouldn't cause any problems for actually building pbrt; does it compile ok?

(It looks like ptex, an external library that pbrt uses checks for doxygen, but I'm not sure why.)

**Comment by miccall** [comment]
@mmp 
I'm not sure .
It`s make many file named "xxx.dir" when I open solution and Build project named "ALL_BUILD"
But I don't know it ok ?

![default](https://user-images.githubusercontent.com/20721387/39293167-c1de2222-496a-11e8-80b8-4c2b18315ff2.JPG)

There are many .tlog , .obj file in them , but I don`t know how to use ?
![image](https://user-images.githubusercontent.com/20721387/39293692-214ef618-496c-11e8-908d-e46bed8cffb4.png)

 I am a beginner about that , could you give me more detials ?
