### ISSUE TITLE
Bad control flow in parser.cpp decodeEscaped

### ISSUE THREAD

**Issue by LegalizeAdulthood** [mmp/pbrt-v3#186]
https://github.com/mmp/pbrt-v3/blob/ed57aff6cbd04af7f2e3b6d98bfc40cce97a8099/src/core/parser.cpp#L73

On this line, `Error` will log the message and then fall through to the next case.  This doesn't seem right...  The same thing can happen with the `default:` case and the `return 0` at the end of the function is marked `NOTREACHED`, but it seems that it can certainly be reached.

**Comment by mmp** [comment]
Thanks!
