### ISSUE TITLE
WIN32 is not defined on x86 platform, Visual Studio 2017

### ISSUE THREAD

**Issue by delguoqing** [mmp/pbrt-v3#191]
x64 platform is ok.

**Comment by mmp** [comment]
Does this caused problems with building pbrt? I see a check for WIN32 in src/core/imageio.cpp. Are there other things that don't compile? Is _WIN32 defined?

**Comment by delguoqing** [comment]
yes. pbrt can't compile.
The error message is:
Can't detect machine endian-ness at compile-time.

_WIN32 is defined but WIN32 is not.

**Comment by mmp** [comment]
I dug into this now, and 32-bit builds with VS2017 works for me. However, I added a check for _WIN32 there in 81fd5fd in any case.
