### ISSUE TITLE
Light from Point light source seems couldn't pass through Glass material 

### ISSUE THREAD

**Issue by myjk1992** [mmp/pbrt-v3#197]
Hi, 

i'm new to pbrt and was trying to render an image where the environment is as follows, (the checkerboard is inside the glass box that contains water)
![image](https://user-images.githubusercontent.com/35457483/43685472-99f3362a-98ee-11e8-88f3-da50e5a5762b.png)

However, the image rendered in a full black image. Could someone help me with this?

My pbrt file is

    LookAt 0 4 0  # eye
             0 0 0  # look at point
             0 0 1  # up vector
    Camera "perspective" "float fov" 30

    Sampler "halton" "integer pixelsamples" 2048

    Integrator "volpath" 

    Film "image" "string filename" ["img1.exr"]
          "integer xresolution" [128] "integer yresolution" [128]

    MakeNamedMedium "water" "string type" "homogeneous"
    #absorption cross section
        "rgb sigma_a" [ 0.006 0.006 0.006]
    #scattering cross section
         	 "rgb sigma_s" [ 0 0 0]

    WorldBegin

    AttributeBegin
    LightSource "point" "point from" [0  4  0] "rgb I" [100 100 100]
    AttributeEnd

    AttributeBegin
    Material "glass"
    MediumInterface "water" ""
    Shape "trianglemesh"
    "integer indices" [0 2 1 0 3 2 0 5 7 0 1 5 1 2 4 1 4 5 3 6 4 3 4 2 7 6 3 7 3 0 7 4 6 7 5 4]
    "point P" [ -50 0 -50   50 0 -50   50 0 50  -50 0 50   50 -40 50   50 -40 -50   -50 -40 50   -50 -40 -50]
    AttributeEnd

    AttributeBegin
      Texture "checks" "spectrum" "checkerboard"
              "float uscale" [7] "float vscale" [6]
	    	  "rgb tex1" [.1 .1 .1] "rgb tex2" [.8 .8 .8]
     Material "matte" "texture Kd" "checks"
     Shape "trianglemesh"
     "integer indices" [0 2 1 0 3 2]	
     "point P" [ -2 -10 -2   2 -10 -2   2 -10 2  -2 -10 2 ]
     "float st" [ 0 0   1 0    1 1   0 1 ]

    AttributeEnd

    WorldEnd

**Comment by sriravic** [comment]
Hi.

This would be because the path vertex at the light source and the glass are both specular (delta) and hence they cannot be connected by direct path sampling strategies (their eval() functions return zero all the time). If you use an area sensor then a light tracer (starting from the light source) might be able to have some rays from the glass hit the sensor but with a pinhole camera, you cannot render this also. 

Try using photon mapping to visualize this scene or use a small area light source instead of a point light source.

**Comment by myjk1992** [comment]
Hi, thanks for your kind reply.

Do you mean using "sppm" integrator instead? It supports photon mapping but doesn't support volume scattering. And in my case, I would like to let the glass box filled with pure water (that would attenuate the light intensity).

Besides, I have tried using area light source but it turned out to render a super noisy image even though I kept increasing the number of samples to more than one hundred thousand :(
