### ISSUE TITLE
Pbrt user interface

### ISSUE THREAD

**Issue by Fact87** [mmp/pbrt-v3#198]
I have tried Pbrt and it is awesome rendering software. It would be nice if a user interface could be made for it instead of manually edit files. Meshes import is already handled by obj2pbrt.
The Vulkan api could be used for the setup window or progressive rendering implemented instead.

**Comment by StudenteChamp** [comment]
Yes i agree this would be very nice. Edit files by hands can be painful.

**Comment by mmp** [comment]
We will likely have a user interface of some sort in the next version.

**Comment by Fact87** [comment]
Will it be for Pbrt v4 or a new v3 release?

**Comment by mmp** [comment]
v4. We don't generally add significant functionality to the system beyond what's described in the book.
