### ISSUE TITLE
Small Typo "PBRT_FLOAT_IS_DOUBLE"

### ISSUE THREAD

**Issue by HiroyukiSakai** [mmp/pbrt-v3#199]
I think I've stumbled upon a small typo in `/src/core/rng.h`, line 55:
`PBRT_FLOAT_IS_DOUBLE` should be replaced with `PBRT_FLOAT_AS_DOUBLE`.

Thanks for the great work!

**Comment by mmp** [comment]
Fixed now--thanks!
