### ISSUE TITLE
"E:\pbrt-v3\build\Release\ALL_BUILD" cannot be started. The system cannot find the specified file.无法启动程序“E:\pbrt-v3\build\Release\ALL_BUILD”,系统找不到指定的文件

### ISSUE THREAD

**Issue by lnwn** [mmp/pbrt-v3#201]
在VS2017（Win10_64bits）上调试pbrt.cpp时显示无法启动程序“E:\pbrt-v3\build\Release\ALL_BUILD”,系统找不到指定的文件，是什么原因呢？求助，谢谢！
When debugging pbrt.cpp on VS2017 (Win10_64bits), it shows that the program "E:\pbrt-v3\build\Release\ALL_BUILD" cannot be started. The system cannot find the specified file. What is the reason? Help, thank you!

**Comment by black6816** [comment]
需要指定工作目录，在项目属性框里。

**Comment by PBRer** [comment]
> 需要指定工作目录，在项目属性框里

> 需要指定工作目录，在项目属性框里。

你说的很有道理，我也尝试过了。我的做法是将pbrt_exe的工作目录换成了“E:\pbrt-v3\build\Release\”仍然报错，后来我有尝试在“调试-ALL_BUILD属性”中更改工作目“E:\pbrt-v3\build\Release\”，还是报错。不知我的操作哪里有问题？还望指教。谢谢。

**Comment by mmp** [comment]
Closing under the expectation that @black6816's suggestion solved the problem.
