### ISSUE TITLE
Is it a wrong param for Curve's hit point calculation

### ISSUE THREAD

**Issue by zq317157782** [mmp/pbrt-v3#217]
sorry for my poor english~.
I have some confuse at the code ` *isect = (*ObjectToWorld)(SurfaceInteraction(
                ray(pc.z), pError, Point2f(u, v), -ray.d, dpdu, dpdv,
                Normal3f(0, 0, 0), Normal3f(0, 0, 0), ray.time, this));` in line 367 of curve.cpp.
the hit point is eq `ray(pc.z)` here,but i think is's  `ray((*tHit))`  but not  `ray(pc.z)` because the `pc.z` is not eq `*tHit` if the length of ray is not normalized.

**Comment by mmp** [comment]
You're right, and thanks for the fix in pr #218!
