### ISSUE TITLE
HairBSDF's beta_m param maybe bring a nan problem

### ISSUE THREAD

**Issue by zq317157782** [mmp/pbrt-v3#219]
In hair.h/cpp I found that when `beta_m` eq zero,the set of roughness variance `v[pMax]`'s elements are alse all zero,and `beta_m` eq zero is a valid param.
But I also found in function`Mp` has code:
`Float a = cosThetaI * cosThetaO / v;
    Float b = sinThetaI * sinThetaO / v;`  that `v` maybe a zero.I think this will cause a **nan** problem maybe.

**Comment by syoyo** [comment]
Actually, there are many places that floating point become NaN(e.g. division by zero) or Inf (e.g. log/exp) in PBRT's hair bsdf implementation.

We have to add nan/inf/zero check in many places in our own hair BSDF module based on PBRT-v3.

**Comment by zq317157782** [comment]
Hi syoyo.
I haven't read the original paper,so I can't ensure these behaviors(NaN/INF/zero) are correct in mathematics based on this hair bsdf model,I think I should cost some time to read this paper.Thanks for comment!
