### ISSUE TITLE
Spectrum.LinearUpsample2x test failed on win10

### ISSUE THREAD

**Issue by YaMaple** [mmp/pbrt-v3#220]
Hello! Pbrt-v3 is awesome, but I have run into a problem.

I built pbrt-v3 on both ubuntu18.04.1 and win10 a few months ago and everything was fine. Yesterday I built pbrt-v3 (I recloned pbrt-v3 yesterday before building it) on ubuntu18.04.1 again and it works well, but after building it on win10 (using the recloned pbrt-v3), I have one failed test in pbrt_test.exe.

I use cmake-gui and vs2017 (up to date version) on win10 to build pbrt-v3 and I didn't modify any configuration setting in cmake-gui.

The output of cmake
https://paste.ubuntu.com/p/wnzJZxFb7c/
The output of vs2017 when building PBRT-V3.sln
https://paste.ubuntu.com/p/FgvcrSmfY5/
The output of pbrt_test.exe
https://paste.ubuntu.com/p/bbZPnNvmWz/
The interface of cmake
![2019-01-14 094042](https://user-images.githubusercontent.com/23411936/51094209-ecd76700-17e5-11e9-9a55-6c074d6b6dad.jpg)
The interface of vs2017
![2019-01-14 094755](https://user-images.githubusercontent.com/23411936/51094213-f660cf00-17e5-11e9-8d6b-ab7712195c6a.jpg)

Thanks in advance!

**Comment by vchizhov** [comment]
You can find this comment inside the code:
`// FIXME: the i=0 case fails with MSVC 2013; it returns 1.125 instead of 1.
// Should chase this down to figure out if it's an edge-case in our
// implementation that happens to work out for other compilers but is
// actually a bug/ambiguous, or if it's a MSVC issue.`
So I think it's safe to assume they are not sure either what's causing the issue.

**Comment by YaMaple** [comment]
> 
> 
> You can find this comment inside the code:
> `// FIXME: the i=0 case fails with MSVC 2013; it returns 1.125 instead of 1. // Should chase this down to figure out if it's an edge-case in our // implementation that happens to work out for other compilers but is // actually a bug/ambiguous, or if it's a MSVC issue.`
> So I think it's safe to assume they are not sure either what's causing the issue.

Oh~Thanks a lot! That's a great relief.

**Comment by r0bbE** [comment]
I had the same problem with VS2019, but only in "Release" Configuration.
Fixed it in this PR https://github.com/mmp/pbrt-v3/pull/249

**Comment by mmp** [comment]
And PR #249 is finally merged, so closing this out...
