### ISSUE TITLE
Hair rendering issue (possible incorrect intersection computation)

### ISSUE THREAD

**Issue by jeffrey89** [mmp/pbrt-v3#221]
I am rendering two hair models. One using the provided hair model from PBRT (straight hair) and the other from CemYuksel (wavy model), converted by using the cy2pbrt tool provided from the PBRT source code.
When I render both models, with a distant light source coming from behind the hair models (shining into the camera), then the hair model from PBRT renders fine, but the hair model from Cem Yuksel does not:

1. The wavy hair model is overlit,
2. It seems that something is going wrong with the intersection computation for the wavy model, since you would only expect the edges of the hair model to be lit (the central part is dense enough to block light light). I even added a head model between the hairs from Cem Yuksel, and such an opaque object is also not blocking the light.

I attached two renderings with a scene description file.

![wavy-straight-lit-from-back](https://user-images.githubusercontent.com/9453513/51382803-0b0bd280-1b18-11e9-91ed-9e220188ccf8.png)
![wavy-straight-lit-from-right](https://user-images.githubusercontent.com/9453513/51382805-0b0bd280-1b18-11e9-8dea-93e9ed34372c.png)

[scene.txt](https://github.com/mmp/pbrt-v3/files/2772642/scene.txt)

**Comment by jeffrey89** [comment]
After building PBRT with the lastest sources I managed to get a correct output. I tried different builds: debug and release, and single precision floating point vs. double precision floating point. The correct result I get with single precision floating precision.

If I build PBRT with double precision floating point (-DPBRT_FLOAT_AS_DOUBLE=1), then the rendered output is still incorrect. Moreover, the output for the PBRT hair model is now incorrect as well. See attachments. 

I don't know why this happens. Maybe any of you has a clue what has changed in the last couple of weeks/months that could result in this behavior?

For what it's worth:
My OS: Linux Mint 18.3 (Sylvia)
My compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
Thread model: posix

![latest_doubleprecision](https://user-images.githubusercontent.com/9453513/51758172-63694400-20c5-11e9-9c45-759c01ad07a5.png)
![latest_singleprecision](https://user-images.githubusercontent.com/9453513/51758175-6401da80-20c5-11e9-96e0-67d9992cd370.png)

**Comment by mmp** [comment]
Sorry for not getting to this sooner (and when I did, it took a while to chase down.)

It boiled down to an Unfortunate Interaction between extra ray origin slop being added in the Float==Double case and the large initial ray origin slop that's necessary with curves..

Fixed now.
