### ISSUE TITLE
Disney microfacet implementation is incorrect

### ISSUE THREAD

**Issue by paulu** [mmp/pbrt-v3#224]
The specular highlights of the disney material are wrong.

The attached test scene consists of a white area light emitter and (1) a red dielectric ball, (2) a black dielectric ball and (3) a copper-like conductor ball (f_0 is [0.9 0.45 0.45]). From basic principles, the expected results are (1) white highlight, (2) white highlight, (3) highlight whose red is approximately twice the green and blue components.

The actual results (with the current master) are (1) red highlight, (2) no highlight and (3) highlight whose red >> 2 * green or 2 * blue.

These results are easily explained by this line of code: ```si->bsdf->Add(ARENA_ALLOC(arena, MicrofacetReflection)(c, distrib, fresnel));``` which incorrectly multiplies the microfacet model by the base color. This causes (1) to pick up the red from the base color (2) to eliminate the highlight and (3) to make the effective material appear darker and applies a gamma-like effect to the relative proportions of the components.

Replacing ```c``` with ```1.f``` achieves the correct result.

[scene.txt](https://github.com/mmp/pbrt-v3/files/2824866/scene.txt)

**Comment by mmp** [comment]
Thanks!!
