### ISSUE TITLE
git.pbrt.org seems to be down

### ISSUE THREAD

**Issue by evil84** [mmp/pbrt-v3#226]
git.exe clone --progress -v "git://git.pbrt.org/pbrt-v3-scenes" "D:\pbrt-v3-scenes"

Cloning into 'D:\pbrt-v3-scenes'...
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... 146.148.96.151 done.
fatal: read error: Invalid argument

**Comment by mmp** [comment]
I rebooted and restarted everything and it seems fine now. Sorry for the inconvenience!

**Comment by hrehfeld** [comment]
Again?

```
git clone --progress -v "git://git.pbrt.org/pbrt-v3-scenes"
Cloning into 'pbrt-v3-scenes'...
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... 146.148.96.151 done.
fatal: read error: Connection reset by peer
```

**Comment by mmp** [comment]
Fixed now. Sorry for the trouble! (We'll switch over to github for the pbrt-v4 scenes in order to avoid this issue in the future...)

**Comment by hrehfeld** [comment]
No problem at all, thanks for fixing it so quickly! :+1: I actually like the decentralized infrastructure, maybe just provide a backup mirror here?

**Comment by Andrew-Helmer** [comment]
This seems to be happening for me right now, I can't download the scenes. Sorry to bother you Matt, I know this will all be obsolete shortly!

**Comment by mmp** [comment]
This should be fixed now--sorry for the inconvenience! (And yes, this is obviously an intentional ploy to encourage migration to pbrt-v4. :-) )

**Comment by Andrew-Helmer** [comment]
Got it, thank you Matt! And yes, I know :-). I will probably port some of what I'm doing to pbrt-v4 before long. I like the new, simpler Sampler interface!
