### ISSUE TITLE
A missing check in MicrofacetTransmission::f

### ISSUE THREAD

**Issue by xiamengqi2012** [mmp/pbrt-v3#228]
I am wondering if MicrofacetTransmission::f is missing a check Dot(wo, wh) * Dot(wi, wh)<0. I think right now it can produce nonzero results when Dot(wo, wh) * Dot(wi, wh)>=0. I observed weird artifacts when I path traced Microfacet layers to render layered materials.

**Comment by mmp** [comment]
You're right--thanks for reporting that, and apologies for the trouble with your work rendering layered materials... Fixed now.
