### ISSUE TITLE
Variable name to index mismatch in AnimatedTransform in transform.cpp

### ISSUE THREAD

**Issue by davechallis** [mmp/pbrt-v3#231]
In the [AnimatedTransform constructor](https://github.com/mmp/pbrt-v3/blob/f7653953b2f9cc5d6a53b46acb5ce03317fd3e8b/src/core/transform.cpp#L396) that computes motion derivate terms, there's a mismatch between the names of some variables and the array indexes they're used to store.

Lines [418 to 427](https://github.com/mmp/pbrt-v3/blob/f7653953b2f9cc5d6a53b46acb5ce03317fd3e8b/src/core/transform.cpp#L418-L427) contain:

        Float t0x = T[0].x;
        Float t0y = T[0].y;
        Float t0z = T[0].z;
        Float t1x = T[1].x;
        Float t1y = T[1].y;
        Float t1z = T[1].z;
        Float q1x = R[0].v.x;
        Float q1y = R[0].v.y;
        Float q1z = R[0].v.z;
        Float q1w = R[0].w;

The first six assignments look correct, but it looks like the last four don't match the array index they're using (i.e. they should be named `q0x`, `q0y` etc.).

Either that, or the variable names are correct and the array index is wrong (i.e. perhaps they should be accessing `R[1]`).

I don't understand the code well enough to know what the intention is here, just noticed that there was a mismatch.

**Comment by mmp** [comment]
Nice catch--fixed!
