### ISSUE TITLE
An implementation question regarding the construction of a BVH

### ISSUE THREAD

**Issue by harrytodorov** [mmp/pbrt-v3#232]
Going through the building of a BVH, I stumbled upon [this line](https://github.com/mmp/pbrt-v3/blob/f7653953b2f9cc5d6a53b46acb5ce03317fd3e8b/src/accelerators/bvh.cpp#L251), which was a bit unclear for me. Why would you use a for-loop just add 1 element?

**Comment by mmp** [comment]
Normally, you wouldn't. :-)

In this case it's an artifact of pbrt being a literate program; [this code fragment](http://www.pbr-book.org/3ed-2018/Primitives_and_Intersection_Acceleration/Bounding_Volume_Hierarchies.html#fragment-CreateleafmonoBVHBuildNode-0) is reused in both places leaf nodes are created (the one-primitive case and in the multi-primitive cases.) That way, we don't have to repeatedly implement the little bit of functionality to grab the primitive number, index into the `primitives` array, etc...
