### ISSUE TITLE
Artifacts with Sobol Sampler

### ISSUE THREAD

**Issue by gonsolo** [mmp/pbrt-v3#236]
I am seeing some artifacts with the Sobol sampler with 32 samples per pixel. They disappear at 64spp. Is this inherent in the Sobol sampler or just a bug? See the attached zip with the scene and two images.

![sobol](https://user-images.githubusercontent.com/2041764/56849105-cc44a000-68f0-11e9-8bec-b3a5e6ee7805.png)

[bug.zip](https://github.com/mmp/pbrt-v3/files/3123808/bug.zip)

**Comment by mmp** [comment]
That's a known issue with the Sobol sampler: that it has structured artifacts like that before convergence.  Here's [another illustration](http://www.pbr-book.org/3ed-2018/Sampling_and_Reconstruction/Sobol_Sampler.html#fig:sobol-vs-halton).
