### ISSUE TITLE
A question regarding the stack size during bvh traversal

### ISSUE THREAD

**Issue by harrytodorov** [mmp/pbrt-v3#239]
I was reading through the source code to traverse a bvh tree, when I stumbled upon the fixed stack you're using [here](https://github.com/mmp/pbrt-v3/blob/f7653953b2f9cc5d6a53b46acb5ce03317fd3e8b/src/accelerators/bvh.cpp#L707). Is there an explanation for it?

My intuition is that you bound it to the maximum depth for a bvh tree you could have? When traversing a bvh tree of depth 64 and you reach a leaf node, at most you would have 64 - 1 elements in the stack.

**Comment by harrytodorov** [comment]
> I was reading through the source code to traverse a bvh tree, when I stumbled upon the fixed stack you're using [here](https://github.com/mmp/pbrt-v3/blob/f7653953b2f9cc5d6a53b46acb5ce03317fd3e8b/src/accelerators/bvh.cpp#L707). Is there an explanation for it?
> 
> My intuition is that you bound it to the maximum depth for a bvh tree you could have? When traversing a bvh tree of depth 64 and you reach a leaf node, at most you would have 64 - 1 elements in the stack.

Ok, I've just read the chapter for traversing a [kd-tree](http://www.pbr-book.org/3ed-2018/Primitives_and_Intersection_Acceleration/Kd-Tree_Accelerator.html#fragment-Preparetotraversekd-treeforray-0) and you state it there as well. It's bound to the tree's maximum depth. Nevertheless, it would be good for a future pedantic reader to be pointed to this piece of information :)

**Comment by mmp** [comment]
I've made a note to add a sentence about that in the next edition. Thanks!
