### ISSUE TITLE
Is there a way to add polarization of light into the PBRT?

### ISSUE THREAD

**Issue by Xie-Jian** [mmp/pbrt-v3#241]
Hi,

Thank you very much for this excellent book and excellent code from the author.

I want to do some experiments on infrared polarization in my master thesis and try to make some modifications to the PBRT to support this idea. Is this feasible, and is there some suggestion as to which changes should be made?

Thank you in advance for your suggestions and look forward to your reply.

**Comment by wangchi87** [comment]
Hi, I have actually tried to do this before, you have to modify the whole spectrum and brdf part to support Stokes Vector and Muller Matrix.

We actually have a open source renderer that support polarisation. http://cgg.mff.cuni.cz/ART/
