### ISSUE TITLE
Physical units in the input file (and in the output image)

### ISSUE THREAD

**Issue by cesss** [mmp/pbrt-v3#243]
Hi!

I'm new to PBRT, and I'm planning to use it for physical validation of different illumination algorithms (I know, a definite physical validation implies real-world measurement from real models, but it does make sense to consider the results from PBRT as another reference to check against).

I wasn't able to find any mention to units in the webpage that describes the input data format (if you search for "units", you get zero results). Does this mean that PBRT is unitless and just expects that the light emission units you choose are coherent with the coordinate (lengths) units? Anyway, the sample scenes seem to define light emission in [0,1] range per component, which doesn't look like true physical units, but conventional values chosen for getting a good rendered image.

Additionally, can I tell PBRT to generate the output as a floating point image whose values have physical units? I mean, absolutely no gamma correction, no color adjustments at all, but just be an image telling you the amount of light in physical units, per component, at each pixel.

Thanks!!

**Comment by mmp** [comment]
If you output to a floating-point format (EXR or PFM), no gamma correction or other adjustments are made to the output values.

The unit of distance measure is implicitly meters, though that isn't particularly enforced. (That comes from the fact that radiance, L, is the unit used to specify the emission of most light sources in pbrt, and that in turn is (partially) based on meters.)

I just double checked, and none of the sample scenes I looked at had lights that were emitting in the [0,1] range; most were substantially above that.

**Comment by mmp** [comment]
(I've made a note to be more clear about this in the next version--thanks for pointing it out!)

**Comment by BrianSwift** [comment]
When documenting units in next version, for Participating media mention that sigma_a and sigma_s are (mm^-1).

**Comment by cesss** [comment]
One more question: What are the units for pixel values (when output in floating point format) ? Are they in radiance units?

Also, can you confirm if PBRT is using **watt per steradian per square metre** as the units for radiance (L, as used for specifying light emission) ?

Thanks!
