### ISSUE TITLE
Want to know the rendered RGB value of a particular point, and that point only

### ISSUE THREAD

**Issue by farhanrw** [mmp/pbrt-v3#251]
Hey, I am sorry if this is to vague, however for my project I would need something where I want to see the RGB color of a particular point from multiple angles. So what I am planning to do is setup the camera, render the scene (the usual), however, instead of getting say, a rendered image of a triangle at the center of the scene, I **just want** the RGB that has been rendered at one of the vertices of the triangle. Then I will change the camera, redo this steps. And keep on doing it. (I will somehow automate this, dont know how yet.) Of course at some camera directions that particular point might be **occluded** so I want something like **black**? Or may manually assign a color as that point is not visible from the camera position. Please guide me through or at least give me some pointers about where to look into. I already am reading the book and going through the source code, but it feels a little far fetched as I am still a novice in PBRT. Thanks!

**Comment by TzuChieh** [comment]
Hi, I think what you are trying to do is something similar to light baking or light probes. The **stochastic progressive photon mapping** integrator (pbrt-v3/src/integrators/sppm.cpp) might be of interest to you. It allows you to store path vertices in the scene and estimate the outgoing radiance from any point, and you can modify the code to force path vertices being triangle vertices. Hope this helps! :grin:

**Comment by mmp** [comment]
Another option: all of the `SamplerIntegrator`s in pbrt have a `Li()` method that returns the radiance along a given ray. Normally, those rays are generated by the camera (called in the `SamplerIntegrator::Render()` method. You could get rid of the camera and instead generate rays toward the vertices of the triangles you were interested in; if they hit those triangles, then `Li()` will give you the radiance leaving in that direction.

(You might want to offset them slightly from the vertices, to be sure that they don't miss the triangles.)

**Comment by farhanrw** [comment]
Thanks Matt for your reply. Is there quick any way to shoot a ray only towards that point? The way I understand is there is a scene object, the rays are shot and the intersections are populated inside the isect object. However, by reading your comment, I was thinking if there is any quicker approach using which I can just shoot rays at specific points, if they can be reached, the radiance is calculated, if not a specific value is returned.

**Comment by mmp** [comment]
There's no built-in functionality for that--you'd have to hack one of the integrators.
