### ISSUE TITLE
Total internal reflection is broken for rough glass

### ISSUE THREAD

**Issue by timo-oster** [mmp/pbrt-v3#254]
Hi,

I noticed that PBRT swallows rays that should be totally internally reflected in rough glass materials. If you create a rough glass box and place it in a completely white InfiniteAreaLight (see attached file), the box should have a uniform color, but PBRT produces dark areas where total internal reflection should be happening.

The reason I believe is that when computing the half vector in `MicrofacetReflection::f`, it is not ensured that it points outwards. However, the `FrDielectric` function relies on this for handling total internal reflection correctly.

The same problem was reported by a user on Google groups [here](https://groups.google.com/forum/#!msg/pbrt/S8FzfUoFoqQ/LhYN0M6ZBAAJ;context-place=forum/pbrt), which also includes a discussion about a possible fix.

[pbrtfile.zip](https://github.com/mmp/pbrt-v3/files/3684723/pbrtfile.zip)

**Comment by mmp** [comment]
Fixed now, and thanks for the clear diagnosis of the problem--that made the fix easy.
