### ISSUE TITLE
dragons.pbrt scene does not render

### ISSUE THREAD

**Issue by ap1** [mmp/pbrt-v3#26]
Minor issue, looks like the lines texture is missing:

dragons.pbrt:24

    Texture "grid" "color" "imagemap" "string filename" ["../../regress/textures/lines.exr"]

Here is the error:

    ~/proj/pbrt-v3/scenes/dragons$ pbrt dragons.pbrt
    pbrt version 3 (built Aug 14 2015 at 12:55:36) [Detected 16 cores]
    Copyright (c)1998-2015 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
    The source code to pbrt (but *not* the book contents) is covered by the BSD License.
    See the file LICENSE.txt for the conditions of the license.
    dragons.pbrt(25): Error: Unable to read "./../../regress/textures/lines.exr": Cannot read file.

**Comment by mmp** [comment]
Fixed with the updated drop of the example scenes at http://mmp.storage.googleapis.com/pbrt/pbrt-v3-scenes.tar.bz2. Thanks for reporting!
