### ISSUE TITLE
About the Example scenes in pbrt-v3 scenes page

### ISSUE THREAD

**Issue by zhang-zy1995** [mmp/pbrt-v3#262]
I can't download the Example scenes through running git clone git://git.pbrt.org/pbrt-v3-scenes or through http://storage.googleapis.com/pbrt/pbrt-scenes.git.tar.gz.
I tried a lot of different ways to download it, but it didn't work. Is the link address no longer available？

**Comment by mmp** [comment]
Thanks for letting me know about this!

I have fixed both of those; please let me know if they aren't working for you now!

Thanks,
Matt
