### ISSUE TITLE
Question about NEE

### ISSUE THREAD

**Issue by deadmarston** [mmp/pbrt-v3#266]
Generally, we do NEE only with the light samping. But it seems that you do the NEE with both light sampling and bsdf sampling. Could you explain the reason why you do that?

thanks
![problem](https://user-images.githubusercontent.com/12645568/70516145-d2367b00-1b79-11ea-8d0d-146481ae28e8.PNG)

**Comment by mmp** [comment]
It's because pbrt does direct lighting using multiple importance sampling. See [here](http://www.pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Direct_Lighting.html#EstimatingtheDirectLightingIntegral).

**Comment by mmp** [comment]
Regarding the difference w.r.t. Mitsuba: pbrt-v3 is a little wasteful. Mitsuba re-uses the same BSDF sample ray for both MIS with direct lighting as well as for indirect illumination. (The next version of pbrt will do it that way as well.)

**Comment by deadmarston** [comment]
thanks
