### ISSUE TITLE
Is it possible to build without embedding external dependencies?

### ISSUE THREAD

**Issue by cesss** [mmp/pbrt-v3#268]
One of the GitHub features I'm not comfortable with is embedding external dependencies. It can be convenient for quickly trying out a project (you download everything recursively, build everything together, and there you go), but when you finish your first glance and you move into seriously using a project, then you need to install it, and you realize that you are duplicating code because you are using the external dependencies for more than one project (and each of them embeds and builds its own copy --although quite often the "install" target is broken in that workflow).

I want to use pbrt tightly integrated in another application, so the first thing is to get a tidy and clean source tree and build workflow, where dependencies are parallel to pbrt (at the same hierarchy level in the source tree and not inside it).

Is it currently possible to invoke Cmake in some way to achieve this?

Of course I could fork pbrt and tune it to my needs, but I prefer to avoid doing that, because when you do your custom modified fork, applying commits from the official fork becomes harder and harder with time...

So, if I could achieve this with the official source, unmodified, it would be great!

**Comment by mmp** [comment]
There's no way to do that currently. For pbrt's purposes, I think it's more important that it be easy to build out-of-the-box on whatever system someone has. However, pull requests that improve the CMakeLists.txt file are always welcome. :-)
