### ISSUE TITLE
Rare events causing NaNs in FourierBSDF::f()

### ISSUE THREAD

**Issue by pgrit** [mmp/pbrt-v3#272]
Hi,

There is a rare event causing NaNs in, e.g., the Bathroom scene from the example scenes repository.

The culprit is the FourierBSDF. It can happen that the incoming / outgoing directions have their x and y components exactly equal to zero. For example, in my case the values were:

```C++
wi.x == 0.0f && wi.y == -0.0f && wi.z = 0.9999994f;
wo.x == 0.0f && wo.y == 0.0f && wo.z = 0.9999994f;
```

The `CosDPhi` function, which sets z to zero and computes the 2D dot product, then produces a NaN. The problem is that the 2D projection of a vector might be the 2D zero vector. In that case, the 2D cosine is undefined. We are dealing with 3D directions, however, so we know that the correct value in that case is 1.

My suggestion would be to add the following check:

```C++
inline Float CosDPhi(const Vector3f &wa, const Vector3f &wb) {
    Float lenSqrA = wa.x * wa.x + wa.y * wa.y;
    Float lenSqrB = wb.x * wb.x + wb.y * wb.y;

    // Prevent NaNs if either vector's 2D projection is the 2D zero vector
    if (lenSqrA == 0.0 || lenSqrB == 0.0) return 1.0f;

    return Clamp(
        (wa.x * wb.x + wa.y * wb.y) / std::sqrt(lenSqrA * lenSqrB),
        -1, 1);
}
```

**Comment by mmp** [comment]
Thanks--fixed!
