### ISSUE TITLE
NaNs in BeckmannDistribution and TrowbridgeReitzDistribution

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v3#273]
Both the BeckmannDistribution and TrowbridgeReitzDistribution divide by the anisotropic alpha values which can result in NaNs if either of those alpha values are 0. This can arise in the following condition:

- A material does not map roughness to alpha, as the RoughnessToAlpha provides a lower bound as part of its calculation.

- alphax or alphay is zero while the other is non zero. (When both are zero a Specular distribution is used.)

An example is attached -

[remap_glass_crash.pbrt.gz](https://github.com/mmp/pbrt-v3/files/4333686/remap_glass_crash.pbrt.gz)

**Comment by mmp** [comment]
Thanks!
