### ISSUE TITLE
Typo on page 938 of pbrt 3rd edition

### ISSUE THREAD

**Issue by abrassel** [mmp/pbrt-v3#282]
In the fourth paragraph of `15.5.9 SETTING SCATTERING PROPERTIES`, the book writes: with rho known, the desired coefficients are given by `sigma_s =rho / sigma_t^-1` and `sigma_s = (1-rho)/sigma_t^-1`.  I believe that the second one should be `sigma_a` based on the utility function defined below.

**Comment by mmp** [comment]
Thanks, though that one was already reported by Per Christensen and is in the online errata..
