### ISSUE TITLE
Ambiguity in SamleCatmullRom2D

### ISSUE THREAD

**Issue by abrassel** [mmp/pbrt-v3#283]
On page 825 of PBRT, Third Edition, the book writes "The rest of [`SampleCatmulRom2D`] is identical to `SampleCatmullRom` except that every access to `values[i]` is replaced by `interpolate(values, i)`."  In SampleCatmullRom, there aren't actually any calls to `values[i]`.

**Comment by mmp** [comment]
Good catch--thanks! I'll have that added to the errata and fixed in the online edition when the next update is pushed online later today.
