### ISSUE TITLE
Using FaceIndex values per pixel

### ISSUE THREAD

**Issue by farhanrw** [mmp/pbrt-v3#284]
Hello,

I want to know the nearest face that the ray intersected for each pixel in the image. I want to write it out to a file. I know there is a faceIndex variable that contain this information in the SurfaceIntersection object. However when I tried I always found that it containts a default value of 0 for each pixel. Is there any way I can make use of it and output the nearest face id for each of the pixels in my render?

**Comment by mmp** [comment]
The face index is a per-triangle property that has to be specified in the scene description and is used as part of Ptex texture mapping. (In other words, it doesn't do what you were expecting.)
