### ISSUE TITLE
Code simplification idea: Allow BxDFs to determine if they are useless

### ISSUE THREAD

**Issue by bhouston** [mmp/pbrt-v3#29]
This is not an important issue, but I was looking at the code for the BxDF creation in the materials.  I noticed patterns like this (pseudo code):

```
// creation of translucent
if( diffuse !== BLACK )
	if( reflectance !== BLACK )
		bsdfs.add( new LambertianReflection( reflectance * diffuse ) );
	if( transmittance !== BLACK )
		bsdfs.add( new LambertianTransmission( transmittance * diffuse ) );

if( specular !== BLACK )
 	var microfacetDistribution = new TrowbridgeReitzDistribution( roughness, roughness );
	if( reflectance !== BLACK )
		var fresnel = new FresnelDielectric( 1, 1.5 );
	 	bsdfs.add( new MicrofacetReflection( reflectance * specular, microfacetDistribution, fresnel ) );
	if( transmittance !== BLACK )
	 	bsdfs.add( new MicrofacetTransmission( transmittance * specular, microfacetDistribution, 1.0, 1.5 ) );
```

If one allowed for BxDFs to state if they are useless, by using looking at their parameters, one could simplify the above to something much more straight forward:

```
// creation of translucent
bsdfs.add( new LambertianReflection( reflectance * diffuse ) );
bsdfs.add( new LambertianTransmission( transmittance * diffuse ) );

var microfacetDistribution = new TrowbridgeReitzDistribution( roughness, roughness );
var fresnel = new FresnelDielectric( 1, 1.5 );
bsdfs.add( new MicrofacetReflection( reflectance * specular, microfacetDistribution, fresnel ) );
bsdfs.add( new MicrofacetTransmission( transmittance * specular, microfacetDistribution, 1.0, 1.5 ) );

bsdfs.removeUselessBxDFs();
```

Basically one could encapsulate into each BxDF class its ability to optimize itself out of the computation.  It is sort of weird that in the creation of the materials one is trying to optimize some BxDFs away, because the material itself is basically trying to understand the internals of the BxDFs and their dependences upon parameters.  One could just encapsulate that decision of whether the BxDF is useless into the material -- probably where it should be.

But then this requires a filtering of the created BxDFs after creation to remove the useless ones, or it requires helper per BxDF factory functions to do conditional creation of BxDFs.  Either way, the code would be cleaner with less breaking of the BxDF encapsulation within the material creation, if that is important.

**Comment by bhouston** [comment]
Probably not important.  Closing.

**Comment by mmp** [comment]
This is a nice idea; another approach could be something like factor methods, like

```
static BxDF *Lambertian::Create(const Spectrum &r)
```

where then the logic about "is this irrelevant" is folded into the Create method, and `nullptr` is returned if the BxDF has no contribution.

Unfortunately the book text is locked down at this point, so it's too late for us to make changes like this to the main interfaces. Maybe for the 4th edition. :-)
