### ISSUE TITLE
Time schedule for pbrt-v4?

### ISSUE THREAD

**Issue by xinwen-cs** [mmp/pbrt-v3#290]
Hi, I am a graphics green hand. I have learn some fundamental knowledege and implemented a rasterizer and ray tracer. I want to know any future plan for pbrt-v4 since v3 is published in 2016. Or any breaking changes?
Thanks

**Comment by mmp** [comment]
pbrt-v4 is on its way; the current plan is to do a pre-release the source code in ~2 months when SIGGRAPH happens, have a beta version of the online book around the new year, and then a printed book out next Spring. It will be substantially updated, though on the other hand, I don't think pbrt-v3 is yet completely obsolete. :-)

**Comment by oscarbg** [comment]
can share if we should expect some GPU support in pbrt-v4?

**Comment by xinwen-cs** [comment]
Thanks! Long live graphics!

**Comment by mmp** [comment]
Yes. :-)

https://www.youtube.com/watch?v=prZJ8FBG9BI&t=6386s <https://www.youtube.com/watch?v=prZJ8FBG9BI&t=6386s>
