### ISSUE TITLE
Potential divide by zero in SpecularReflection?

### ISSUE THREAD

**Issue by chrisguiney** [mmp/pbrt-v3#299]
Hi,

I think there's a divide-by-zero in `SpecularReflection::Sample_f`: https://github.com/mmp/pbrt-v3/blob/master/src/core/reflection.cpp#L142

if `AbsCosTheta(*wi)` returns zero (that is, if `wo.z` happens to be exactly zero), then the result would be positive infinity.

Admittedly, I haven't tried to reproduce this in pbrt-v3 directly -- I discovered it in my own implementation.  

I'm certainly an amateur when it comes to rendering, so assuming that I'm missing something,  I'd be very grateful if someone could provide an explanation on why this isn't an issue.

Or if it is actually an issue, perhaps give some guidance on how to fix it?  I'd gladly invest some of my own time to put a test case together & submit a pull request.

Thanks!

**Comment by mmp** [comment]
Good thinking, and you're right that that can (rarely) be an issue.

In pbrt, that should be prevented by this check, which happens before the
Sample_f method is called, so as far as I know, it's not an issue there:

https://github.com/mmp/pbrt-v3/blob/aaa552a4b9cbf9dccb71450f47b268e0ed6370e2/src/core/reflection.cpp#L746

**Comment by chrisguiney** [comment]
Thanks for highlighting this for me!  it was indeed what i was looking for.  

sorry for the delay on the reply, it fell off my radar, and just wanted to close the loop & ticket
