### ISSUE TITLE
pbrt scenes: unable to clone (read error)

### ISSUE THREAD

**Issue by pprabhu78** [mmp/pbrt-v3#303]
Hi,
Trying to clone the pbrt scenes. I get this error:

git.exe clone --progress -v "git://git.pbrt.org/pbrt-v3-scenes"
Cloning into 'pbrt-v3-scenes'...
Looking up git.pbrt.org ... done.
Connecting to git.pbrt.org (port 9418) ... 146.148.96.151 done.
fatal: read error: Invalid argument

I tried other protocols, no success. I tried the snapshot, but I can't pull from that either (I get the same error). I tried with tortoise git as well as command line.

**Comment by mmp** [comment]
Fixed now--apologies for not doing it sooner. (I had to reboot the server.)

**Comment by pprabhu78** [comment]
It works. Thank you so much.

As an aside, I have read, enjoyed and recommended the pbrt book for almost
15 years now.

In my former life I was a researcher. We were working on using gpgpu to do
ray tracing, photon mapping, etc. And yoru book was a great reference.

Ofcourse, now you can do that using dxr, vulkan. But it continues to be a
standard book on whenever I need to look up canon on ray tracing.

-Poojan

**Comment by mmp** [comment]
Thank you! That's great to hear.

(FWIW the next version [pbrt-v4][https://github.com/mmp/pbrt-v4) now optionally supports the GPU via OptiX and CUDA.)

**Comment by pprabhu78** [comment]
That's good to know (about Optix and CUDA)
