### ISSUE TITLE
Scene files for figures in the book

### ISSUE THREAD

**Issue by varun19299** [mmp/pbrt-v3#304]
Are the scene files corresponding to figures in the Pbrt book (v3) accessible online?

**Comment by mmp** [comment]
Mostly no, unfortunately. Some of the scene description files for figures are in the pbrt-v3-scenes distribution (Files names f{x}-{y}.pbrt corresponds to Figure x.y.) Many of the images were rendered with previous versions of pbrt, require a modified version of the system to render them, or have just been lost over time, unfortunately.

I'm happy to make the Illustrator files for the figures in the online version of the book available if that's useful, but the illustrations in the printed book are still owned by the publisher.
