### ISSUE TITLE
Unable to clone the scenes repository at git://git.pbrt.org/pbrt-v3-scenes

### ISSUE THREAD

**Issue by calvin-godfrey** [mmp/pbrt-v3#305]
I went to [https://pbrt.org/scenes-v3.html](https://pbrt.org/scenes-v3.html) and tried both copying the command `git clone git://git.pbrt.org/pbrt-v3-scenes` and typing it out myself. Both resulted in the following error:

```
$ git clone git://git.pbrt.org/pbrt-v3-scenes
Cloning into 'pbrt-v3-scenes'...
fatal: read error: Invalid argument
```
I was able to download from the secondary host (http://storage.googleapis.com/pbrt/pbrt-scenes.git.tar.gz), but is there anything else I have to do to clone the scenes repo? I can clone other git repositories with no issues on the same client, using Git Bash on Windows 10.

**Comment by calvin-godfrey** [comment]
As a follow up question, I unzipped and untarred the download from the secondary host and found most of the data in a `pack-d4ebedc0b1b8f82452ba731732ed21d294e5ca7f.pack` which 7zip says "Can not open file as archive". How can I unpack the .pack file?

**Comment by mmp** [comment]
Sorry about that! This should be fixed now--thanks for reporting it.

The .tar.gz file contains the git repository. Run `git checkout .` to check out the contents.
