### ISSUE TITLE
Git repository and CDN does not work

### ISSUE THREAD

**Issue by zoack** [mmp/pbrt-v3#317]
Hi,
I am trying to download the scene repository and is offline: 
`git clone git://git.pbrt.org/pbrt-v3-scenes`
![imagen](https://user-images.githubusercontent.com/1114800/149839963-2fedaa05-112b-4385-ae4c-f795519d8ccc.png)
 
Downloading the tar from the CDN and starting the project does not seem to work either:
http://storage.googleapis.com/pbrt/pbrt-scenes.git.tar.gz
`git checkout`
The output of the checkout command:
[checkout_output.txt](https://github.com/mmp/pbrt-v3/files/7884787/checkout_output.txt)

**Comment by mmp** [comment]
The git.pbrt.org site is now back up and accepting git connections--sorry for the bother.

On the git checkout, it looks like you're missing the '.' argument--it should be:
```bash
$ git checkout .
```

**Comment by zoack** [comment]
Thanks
