### ISSUE TITLE
How to run rendering on GPU instead of CPU (pbrt v3)

### ISSUE THREAD

**Issue by USMANHEART** [mmp/pbrt-v3#323]
Hi, I am new in pbrt.
I have my own 3D modeling software and also written my own scripts to convert my models to pbrt format.
I am trying to render my pbrt models by using Windows OS command line.

`.\pbrt.exe Sphere.pbrt --outfile Sphere.png`

But this is only using my CPU. How can I enable GPU instead of CPU? Kindly guide me if I am doing wrong.

![image](https://user-images.githubusercontent.com/46762805/176925155-cc70e829-34c8-4603-8c54-13e3e642a6e3.png)

**Comment by mmp** [comment]
pbrt-v3 has no support for GPU rendering. You might consider trying [pbrt-v4](https://github.com/mmp/pbrt-v4).
