### ISSUE TITLE
win10/Visual studio 2019 install

### ISSUE THREAD

**Issue by tempdeltavalue** [mmp/pbrt-v3#330]
I cannot find inside vs 2019 "Where to build the binaries" option

**Comment by mmp** [comment]
When you run cmake's GUI on windows, it should look something like this, where the second line is "Where to build the binaries". What does it look like on your system?

![image](https://github.com/mmp/pbrt-v3/assets/102567/d466af2f-39a5-4db2-91a4-5d948e8017f8)

**Comment by tempdeltavalue** [comment]
@mmp 

Thank you for your answer (and sorry for such delay) 
After cmake generation I see something like that 
![Screenshot 2023-08-27 224818](https://github.com/mmp/pbrt-v3/assets/36921178/49c6e108-28fc-49e7-be8f-466050a9e446)


And here's the log
[log.txt](https://github.com/mmp/pbrt-v3/files/12448705/log.txt)

sln file wasn't generated (VS 19)

**Comment by tempdeltavalue** [comment]
@mmp hi, sorry for delay and thank you for your answer , I generated sln file, when I try to run I get this error 

![Screenshot 2023-08-27 230721](https://github.com/mmp/pbrt-v3/assets/36921178/4bbfc588-9f77-4dbb-bd51-af84d6b4930e)

according to [this ](https://stackoverflow.com/questions/31891067/access-denied-running-program-in-visual-studio)
I set  'Set as Startup project' but after that I get this one 
![Screenshot 2023-08-27 230752](https://github.com/mmp/pbrt-v3/assets/36921178/09031b46-58b3-41b4-9790-c5f5d1cb0764)

In cmake GUI I'm used default win64 generator and I'm running sln for x64 (in debug mode)

**Comment by kennyalive** [comment]
![image](https://github.com/mmp/pbrt-v3/assets/4964024/dacf7916-a61d-4386-95bf-3473295d4322)

**Comment by tempdeltavalue** [comment]
@kennyalive Thank you !
