### ISSUE TITLE
pbrt-v3 exr bug with small images

### ISSUE THREAD

**Issue by wjakob** [mmp/pbrt-v3#43]
Fabrice Rousselle reported the following issue:

> I've run into a strange bug with PBRT that I believe is actually a tinyexr one. I was rendering a 33x33 image of the cornell box scene and the bottom line of pixels was garbage. It worked fine for 32x32 or 34x34 images though. Looking into it some more, I tried with other sizes and it seems that anything smaller than 10x10 pixels produces garbage for the whole image plane. The content of the buffer though is valid up to the point that it's passed to the SaveMultiChannelEXRToMemory method.

> I suspect that the bug is due to the ZIP compression of tinyexr, but it's not clear to me how to disable the compression in the code, so I couldn't verify it. The latest version of tinyexr on github is also quite different from the one in pbrt-v3 (it's now a single header file), and I didn't try it either.

> If you know a way of disabling the compression, I would be very interested, otherwise I'll try using ILM's OpenEXR library instead for now.

> I'm attaching my fancy cbox.pbrt file which produces a 3x3 rendering if you want to reproduce the issue (maybe it's linux specific?), as well as the exr files I obtained at 3x3 and 33x33 resolutions.

The attachment is a Base64 encoded zip file (GitHub file upload only allows a few file formats like PNG and PDF and doesn't like ZIP):

[Archive.txt](https://github.com/mmp/pbrt-v3/files/19355/Archive.txt)

**Comment by wjakob** [comment]
And a follow-up:

> To follow up on my small EXR bug, I just added another WriteEXR method that uses ILM's openexr library instead of tinyexr, and the output files are now correct at all resolutions.

I also had issues with tinyexr not being able to open textures saved as EXRs (the compression formats it can handle are limited). 

IMHO it might be a good to revert back to the old OpenEXR I/O path. A while ago I made an OpenEXR "fork" with a sanitized CMake build which might be useful for that. It that can be included using add_subdirectory() from another project. (https://github.com/wjakob/openexr)

**Comment by mmp** [comment]
Reverting back to OpenEXR sounds good to me at this point. I do think it's important that we have the OpenEXR sources checked into our tree and have things wired up in the cmake files, so that building remains as straightforward as it is now.

**Comment by syoyo** [comment]
I digged into this issue and found the problem looks like a EXR library/viewer using ILM's OpenEXR.

For small image (e.g. 33x33), it will have a small pixel block(33x1), and compressing such a small data may create larger compressed size than input(e.g. 220 bytes compressed, 198 input). Saved EXR image is correct, but reading it in a viewer/library using OpenEXR will create garbage pixel data. 

As a proof, I ran exr2hdr https://github.com/syoyo/tinyexr/tree/master/examples/exr2rgbe converter for 33x33 cornellbox EXR file, and get correct HDR(RGBE) image(i.e. no garbage pixels).

![exr-gabage](https://cloud.githubusercontent.com/assets/18676/10887841/762dd34e-81cc-11e5-9ecc-3102b64df7c5.png)


So, this would be a bug in ILM's OpenEXR 1.x implementation of decoding ZIP compressed image.

The solution(workaround) would be using different compression(e.g. NONE or PIZ) for small image, and fortunately recently I added a support for selecting compression type when saving EXR :-)

https://github.com/syoyo/tinyexr/commit/15689c84f233ca8e66d73fe6969aed3847784899

**Comment by mmp** [comment]
I updated tinyexr and updated the image writing code to not use compression if either dimension is <64 pixels. I hope this fixes the issue.

**Comment by syoyo** [comment]
Cool!

**Comment by wjakob** [comment]
Addressed by PR #49.
