### ISSUE TITLE
BVH SAH possible issue

### ISSUE THREAD

**Issue by KammutierSpule** [mmp/pbrt-v3#47]
I am using the pbrt-v3 bvh.cpp ported to my raytracer and i am building it on linux and windows (mingGW) on Linux all SPLIT methods work, on Windows, the SAH is giving me problems..
Apart that I could still have issues in my ported source code, I was looking and found that in this line in original source:

https://github.com/mmp/pbrt-v3/blob/master/src/accelerators/bvh.cpp#L356

I was expecting that it "return node;" at that point, since it just created a leaf. As it is now, it will fall and init an interior that I believe it is not correct.

**Comment by mmp** [comment]
Nice find--fixed!
