### ISSUE TITLE
error when writing image to .pfm file format

### ISSUE THREAD

**Issue by NielsBillen** [mmp/pbrt-v3#50]
When specifying a `Film`s image filename with the .pfm extension, PBRT will state that the image format is not supported.

This due to an implementation error, where the code which checks the extension is incorrect:

**Original code**

    if (HasExtension(name, ".exr")) {
        WriteImageEXR(name, rgb, resolution.x, resolution.y, totalResolution.x,
                      totalResolution.y, outputBounds.pMin.x,
                      outputBounds.pMin.y);
    } else if (HasExtension(name, ".exr")) {
        WriteImagePFM(name, rgb, resolution.x, resolution.y);
    } 

**Fixed code**

    if (HasExtension(name, ".exr")) {
        WriteImageEXR(name, rgb, resolution.x, resolution.y, totalResolution.x,
                      totalResolution.y, outputBounds.pMin.x,
                      outputBounds.pMin.y);
    } else if (HasExtension(name, ".pfm")) {
        WriteImagePFM(name, rgb, resolution.x, resolution.y);
    }

**Comment by wjakob** [comment]
ouch -- thanks for catching that!

**Comment by wjakob** [comment]
fixed.
