### ISSUE TITLE
Does not compile under GCC 4.7 CentOS 6.6

### ISSUE THREAD

**Issue by Delwin9999** [mmp/pbrt-v3#6]
Clean checkout of master
execute 'make' in directory 'src'.
Error log:

In file included from core/api.cpp:114:0:
./media/grid.h: In constructor ‘GridDensityMedium::GridDensityMedium(const Spectrum&, const Spectrum&, Float, int, int, int, const Transform&, const Float*)’:
./media/grid.h:60:42: error: use of deleted function ‘std::unique_ptr<_Tp [], _Dp>::unique_ptr(_Up*, typename std::enable_if<std::is_convertible<_Up*, _Tp*>::value>::type*) [with _Up = float; _Tp = const float; _Dp = std::default_delete<const float []>; typename std::enable_if<std::is_convertible<_Up*, _Tp*>::value>::type = void]’
In file included from /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/memory:86:0,
                 from core/pbrt.h:60,
                 from core/api.h:43,
                 from core/api.cpp:36:
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/bits/unique_ptr.h:433:2: error: declared here
In file included from ./lights/goniometric.h:47:0,
                 from core/api.cpp:66:
core/mipmap.h: In instantiation of ‘MIPMap<T>::MIPMap(const Point2i&, const T*, bool, Float, ImageWrap) [with T = RGBSpectrum; Point2i = Point2<int>; Float = float]’:
./lights/goniometric.h:65:74:   required from here
core/mipmap.h:135:9: error: call of overloaded ‘ParallelFor(MIPMap<T>::MIPMap(const Point2i&, const T*, bool, Float, ImageWrap) [with T = RGBSpectrum; Point2i = Point2<int>; Float = float]::<lambda(int)>, int&, int)’ is ambiguous
core/mipmap.h:135:9: note: candidates are:
In file included from core/api.cpp:37:0:
core/parallel.h:49:6: note: void ParallelFor(const std::function<void(int)>&, int, int)
core/parallel.h:53:6: note: void ParallelFor(const std::function<void(int, int)>&, int, int)
In file included from ./lights/goniometric.h:47:0,
                 from core/api.cpp:66:
core/mipmap.h:160:9: error: call of overloaded ‘ParallelFor(MIPMap<T>::MIPMap(const Point2i&, const T*, bool, Float, ImageWrap) [with T = RGBSpectrum; Point2i = Point2<int>; Float = float]::<lambda(int, int)>, int&, int)’ is ambiguous
core/mipmap.h:160:9: note: candidates are:
In file included from core/api.cpp:37:0:
core/parallel.h:49:6: note: void ParallelFor(const std::function<void(int)>&, int, int)
core/parallel.h:53:6: note: void ParallelFor(const std::function<void(int, int)>&, int, int)
In file included from ./lights/goniometric.h:47:0,
                 from core/api.cpp:66:
core/mipmap.h:196:9: error: call of overloaded ‘ParallelFor(MIPMap<T>::MIPMap(const Point2i&, const T*, bool, Float, ImageWrap) [with T = RGBSpectrum; Point2i = Point2<int>; Float = float]::<lambda(int)>, int&, int)’ is ambiguous
core/mipmap.h:196:9: note: candidates are:
In file included from core/api.cpp:37:0:
core/parallel.h:49:6: note: void ParallelFor(const std::function<void(int)>&, int, int)
core/parallel.h:53:6: note: void ParallelFor(const std::function<void(int, int)>&, int, int)
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register" [enabled by default]
make: *** [objs/core_api.o] Error 1

It looks like two main errors:
1) GCC 4.7 is not able to disambiguate void(int) from void(int, int) in the template parameter of ParallelFor.
2) From a quick glance at the GridDensityMedium class it looks like you've got a non-default constructor defined but do not explicitly declare the move assignment operator. I haven't tracked it down yet but it looks like there's an assignment somewhere that GCC 4.7 is not converting to a move and the unique pointer is preventing that.

**Comment by mmp** [comment]
I believe that #2 has been fixed and I think #1 may have been fixed, but am less confident about that one. If you have a chance to try again with top of tree and report how it goes, I'd appreciate it!

**Comment by Delwin9999** [comment]
pbrt-v3/src/integrators/bdpt.h:149:29: error: member ‘EndpointInteraction Vertex::<anonymous struct>::ei’ with constructor not allowed in anonymous aggregate

pbrt-v3/src/integrators/bdpt.h:150:27: error: member ‘MediumInteraction Vertex::<anonymous struct>::mi’ with constructor not allowed in anonymous aggregate

pbrt-v3/src/integrators/bdpt.h:151:28: error: member ‘SurfaceInteraction Vertex::<anonymous struct>::isect’ with constructor not allowed in anonymous aggregate

pbrt-v3/src/core/mipmap.h:135:9: error: call of overloaded ‘ParallelFor(MIPMap<T>::MIPMap(const Point2i&, const T*, bool, Float, ImageWrap) [with T = RGBSpectrum; Point2i = Point2<int>; Float = float]::<lambda(int)>, int&, int)’ is ambiguous
pbrt-v3/src/core/mipmap.h:135:9: note: candidates are:
In file included from pbrt-v3/src/core/api.cpp:37:0:
pbrt-v3/src/core/parallel.h:49:6: note: void ParallelFor(const std::function<void(int)>&, int, int)
pbrt-v3/src/core/parallel.h:53:6: note: void ParallelFor(const std::function<void(int, int)>&, int, int)

Also a warning right at the end
pbrt-v3/src/tests/bitops.cpp:23:7: warning: converting ‘false’ to pointer type for argument 1 of ‘char testing::internal::IsNullLiteralHelper(testing::internal::Secret*)’ [-Wconversion-null]

It looks like neither are fixed.  This is after a clean -xdf, pull against master and re-running cmake and make.

Is ac19125 the proper commit for the head of master?  I'm wondering if maybe I didn't get the right code.

**Comment by Delwin9999** [comment]
Gah, not kidding about every button being dangerous.

**Comment by Delwin9999** [comment]
OK, updated to 1eaa295 and the union issues are gone.  Only thing preventing compiling now is the ambiguous overload between 

pbrt-v3/src/core/parallel.h:49:6: note: void ParallelFor(const std::function\<void(int)\>&, int, int)

and 

pbrt-v3/src/core/parallel.h:53:6: note: void ParallelFor(const std::function\<void(int, int)\>&, int, int)

**Comment by Delwin9999** [comment]
I found a stackoverflow that mentions why overloading on std::function is delicate.

http://stackoverflow.com/questions/22542780/c11-auto-stdfunction-and-ambiguous-call-to-overloaded-function

**Comment by mwkm** [comment]
For the ParallelFor(), it iooks like the same for Windows side on VS2015 RC, I applied casts and they are gone.

**Comment by mmp** [comment]
Both the anonymous union and the ParallelFor issue should be fixed in top of tree now, so I'm optimistically closing this. Please reopen this if you're still seeing issues (and sorry for the delay!)
