### ISSUE TITLE
Windows build fails if flex and bison are found.

### ISSUE THREAD

**Issue by ap1** [mmp/pbrt-v3#60]
The following lines in CMakeLists.txt create a version of pbrtlex.cpp that does not compile on Windows (with MSVC 2015). Two of the issues encountered are:

* The escape character (\\) in the inline bash statement (` bash -c ...`) is not needed
* The generated pbrtlex.cpp contains references to unistd.h and is generally unusable.

Removing the `IF(BISON_FOUND AND FLEX_FOUND)` part of the conditional fixes the build.

```
# Optionally use Bison and Flex to regenerate parser files
# Use pregenerated files otherwise (may be outdated)
FIND_PACKAGE ( BISON )
FIND_PACKAGE ( FLEX )
IF(BISON_FOUND AND FLEX_FOUND)
  SET(BisonOutput ${CMAKE_BINARY_DIR}/pbrtparse.cpp)
  ADD_CUSTOM_COMMAND(
    OUTPUT ${BisonOutput} ${CMAKE_BINARY_DIR}/pbrtparse.hh
    DEPENDS ${CMAKE_SOURCE_DIR}/src/core/pbrtparse.yy
    COMMAND ${BISON_EXECUTABLE} -d -v -t
            --output=${BisonOutput}
            ${CMAKE_SOURCE_DIR}/src/core/pbrtparse.yy
    COMMAND bash -c "if [[ -e ${CMAKE_BINARY_DIR}/pbrtparse.hpp ]]; then /bin/mv ${CMAKE_BINARY_DIR}/pbrtparse.hpp ${CMAKE_BINARY_DIR}/pbrtparse.hh; fi"
    COMMENT "Generating pbrtparse.cpp and pbrtparse.hh"
  )

  SET(FlexOutput ${CMAKE_BINARY_DIR}/pbrtlex.cpp)
  ADD_CUSTOM_COMMAND(
    OUTPUT ${FlexOutput}
    DEPENDS ${CMAKE_BINARY_DIR}/pbrtparse.hh ${CMAKE_SOURCE_DIR}/src/core/pbrtlex.ll
    COMMAND ${FLEX_EXECUTABLE}
            -o${FlexOutput}
            ${CMAKE_SOURCE_DIR}/src/core/pbrtlex.ll
    COMMENT "Generating pbrtlex.cpp"
  )

  SET ( PBRT_YACC_LEX_SOURCE
    ${BisonOutput}
    ${FlexOutput}
    )
ELSE()
  SET ( PBRT_YACC_LEX_SOURCE
    src/core/pbrtlex.cpp
    src/core/pbrtparse.cpp
    )
ENDIF()
```

**Comment by mmp** [comment]
The unistd issue should now be fixed.
Does Windows give an error with those semicolons there? They seem to be required for OSX.

**Comment by ap1** [comment]
Thanks!
Windows (specifically gnuwin32 version of bash, mv, if) complain about the backslashes (`\`), not the semicolon. Removing the backslashes fixes the problem.

**Comment by mmp** [comment]
This should be fixed now (please take a look reopen this if not!)

Thanks!

**Comment by ap1** [comment]
Thank you! I will keep an eye on this :+1:
