### ISSUE TITLE
Build issues on Windows

### ISSUE THREAD

**Issue by lookup1980** [mmp/pbrt-v3#64]
Hi,

I tried pbrt-v3 on Windows, and there're 2 build issues:

1. bash command in CMake does not work well on Windows:
` COMMAND bash -c "if [[ -e ${CMAKE_BINARY_DIR}/pbrtparse.hpp ]]\; then /bin/mv ${CMAKE_BINARY_DIR}/pbrtparse.hpp ${CMAKE_BINARY_DIR}/pbrtparse.hh\; fi"`
The command below works, and it should be portable to Linux and OSX:
` COMMAND ${CMAKE_COMMAND} -E rename ${CMAKE_BINARY_DIR}/pbrtparse.hpp ${CMAKE_BINARY_DIR}/pbrtparse.hh`

2. The project can't build with VisualStudio2012, which does not have header file `cinttypes `. VisualStudio2015 works for me.

**Comment by mmp** [comment]
1. Should be fixed now (with a slightly different fix, but thanks for letting me know about "cmake -E rename!"

2. VS2012's C++11 support is almost certainly too incomplete to support pbrt-v3--we use too many C++11 features. (Even getting VS2013 to build it is still a work in progress...)
