### ISSUE TITLE
cmake handling of flex and bison possible issues?

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v3#7]
I think there are a few small issues with the flex and bison stuff in CMakeLists.txt.

- I think the outputs of bison should also include pbrtparse.hh.
- Bison is annoying, since on some platforms it uses .hh for the suffix of the generated header file, on others it uses .hpp, etc. pbrtlex.ll #includes pbrtparse.hh. Before, the makefile would check the suffix generated by bison and rename the header file if needed (https://github.com/mmp/pbrt-v3/blob/8e23330a3db5e7abe0152f0844824728d8f03d13/src/Makefile#L153).
- The output of the bison rule should probably be named pbrtparse.cpp, rather than pbrtparser.cpp, for consistency with the naming of the .yy file.
- I think but am not sure that the flex rule needs an explicit dependency to the pbrtparse.hh output of the bison rule so that it doesn't try to compile pbrtlex.cpp before the bison rule has run. (I'm not positive about this; maybe flagging the .hh output is enough.)
- Is it definitely the case that when running the flex/bison rules, the pbrtparse.hh generated by bison (vs the one checked into src/core) is used? It'll be a really ugly/hard to chase down bug if the user has made modifications to the .yy file but then the wrong header is used.

(CC @nyue )

**Comment by nyue** [comment]
I plan to address all the above over the next couple of days.

For the last point, is it possible to restructure the directory and move (keeping them in the repository) the generated files (*.cpp, *.hpp.*.hh) to a different directory. This should eliminate the danger of implicit "#include" for current directory if "" is used instead of <>. Note though that *.yy and *.ll should stay where they are. This may break the Makefile/SConstruct but if the intention is to replace them with CMake, I guess that is ok.

**Comment by mmp** [comment]
(I think the first three have been addressed so far already.)  Sounds good on the last one.

The Makefile and SConstruct file have already been deleted; it's cmake only at this point. :-)

**Comment by Vertexwahn** [comment]
I suggest to use flex/bison_target since calling bash does not work on Windows.

```cpp
cmake_minimum_required(VERSION 3.2.2)
project(BisonEXPRESS)

find_package(BISON)
find_package(FLEX)

bison_target(Parser ${CMAKE_CURRENT_SOURCE_DIR}/parser.y ${CMAKE_CURRENT_BINARY_DIR}/parser.cpp)
flex_target(Scanner ${CMAKE_CURRENT_SOURCE_DIR}/tokens.l  ${CMAKE_CURRENT_BINARY_DIR}/lexer.cpp)
add_flex_bison_dependency(Scanner Parser)

include_directories(${CMAKE_CURRENT_SOURCE_DIR})
include_directories(${CMAKE_CURRENT_BINARY_DIR})

add_executable(BisonEXPRESS
	eExpressTokenType.h
	tokens.l 
	parser.y
	${FLEX_Scanner_OUTPUTS} 
	${BISON_Parser_OUTPUTS}
	main.cpp
)
```

see also: https://bitbucket.org/Vertexwahn/cmakedemos/src/d59adac85d86/BisonEXPRESS/?at=default

**Comment by mwkm** [comment]
CMake's platform independent Detect and Rename can be achieved like this:

if( EXISTS ${CMAKE_SOURCE_DIR}/core/pbrtparse.hpp )
	MESSAGE( "Renaming core/pbrtparse.hpp to core/pbrtparse.hh" ) 
	file( RENAME ${CMAKE_SOURCE_DIR}/core/pbrtparse.hpp ${CMAKE_SOURCE_DIR}/core/pbrtparse.hh )
endif()
if( EXISTS ${CMAKE_SOURCE_DIR}/core/pbrtparse.cpp.h )
	MESSAGE( "Renaming core/pbrtparse.cpp.h to core/pbrtparse.hh" ) 
	file( RENAME ${CMAKE_SOURCE_DIR}/core/pbrtparse.cpp.h ${CMAKE_SOURCE_DIR}/core/pbrtparse.hh )
endif()

**Comment by Vertexwahn** [comment]
```
bison_target(Parser ${CMAKE_CURRENT_SOURCE_DIR}/pbrtparse.yy ${CMAKE_CURRENT_BINARY_DIR}/pbrtparse.cpp
	 COMPILE_FLAGS --defines="${PROJECT_BINARY_DIR}/pbrtparse.hh")
```
should save the day ;)

**Comment by mwkm** [comment]
the --defines flag works great :)

**Comment by juliendehos** [comment]
It's probably not the top priority but to compile with openbsd, I had to change CMakeLists.txt(44):
-o${FlexOutput}
then run: 
CXX=eg++ cmake ..

**Comment by juliendehos** [comment]
To compile with freebsd, I had to use the same defines as for PBRT_IS_OSX and add "-pthread" in CMakeLists.txt(15) (but I'm not sure this is portable).
With debian 8, I also had to add "-pthread".

**Comment by mmp** [comment]
I believe that all of these issues have been fixed (though sometimes with different approaches, e.g. `FIND_PACKAGE ( Threads )` for the pthreads stuff. Please re-open (or open a new issue) if that's not so.
