### ISSUE TITLE
Curve Intersection Maximum Depth

### ISSUE THREAD

**Issue by sriravic** [mmp/pbrt-v3#76]
The curve intersection routine currently implemented follows the paper by 'Koji Nakamaru and Yoshio Ono'. The maximum recursion depth computed as a part of the intersection routine in line 149 (https://github.com/mmp/pbrt-v3/blob/master/src/shapes/curve.cpp#L149) actually has a probable bug.

The original paper computes **r0 = sqrt(2) * N(N-1) * L0 / (8 * epsilon)**. Since we assume only cubic Beziers, N = 3 here and hence N*(N-1) actually would be 6 . However the current code has 12 which might result in a larger recursion depth being computed than what is necessary. Increased recursion would not result in an error, however might result in wasted computation.

**Comment by mmp** [comment]
Interesting--nice find! I've fixed the code.

FWIW I added some counters to the Curve class to measure how much refinement changed with this fix--on the furry bunny test scene, it went from ~1.8x on average to ~1.6x (IIRC); not a huge difference, but I guess not unexpected given that the log of that value is then taken.

Thanks!
