### ISSUE TITLE
Purpose of CorrectShadingNormal

### ISSUE THREAD

**Issue by L2Program** [mmp/pbrt-v3#78]
Hi, just wondering what the intuition is behind CorrectShadingNormal in BDPT.cpp, line 54. I gather that it is to compensate for the potential difference in normals due to phong interpolation, but I cannot find any sources in the literature about such a correction coefficient. Why is it only needed to light traced paths?

https://github.com/mmp/pbrt-v3/blob/master/src/integrators/bdpt.cpp#L54

Thanks,
Joss

**Comment by mmp** [comment]
Adjoint light transport is a little unusual. See this paper and in particular section 3.2: https://graphics.stanford.edu/papers/non-symmetric/paper-sv.ps

(There will be coverage of this in the 3rd edition book text.)

**Comment by L2Program** [comment]
Thanks for the response, Matt. The discontinuity example on page 9 really cleared this up for me. Cheers.
