### ISSUE TITLE
Compilation error on Raspbian

### ISSUE THREAD

**Issue by koiava** [mmp/pbrt-v3#86]
Compilation failed in imageio.cpp with message "Can't detect machine endian-ness at compile-time."
# define **LITTLE_ENDIAN** solves that locally(which isn't a solution of course) and rest of the compilation is successful.

**Comment by mmp** [comment]
Thanks for reporting this. I believe that I've fixed it in top of tree, but please confirm.

Note that your renders will be quite slow on that target. :-)

**Comment by koiava** [comment]
Now It compiles.
It also gives warning in memory.h everywhere, where it's included direcly or indirectly
> 
pbrt-v3/src/core/memory.h:59:5: warning: requested alignment 128 is larger than 64 [-Wattributes]
     MemoryArena {
     ^
> 

> 
Note that your renders will be quite slow on that target. :-)
> 
:D Fast enough to have fun.
[dining-room](https://benedikt-bitterli.me/resources/pbrt-v3/dining-room.zip) from Benedikt's  repository with 1spp took 71sec. (It's raspberry pi3)
