### ISSUE TITLE
Bump mapping is broken

### ISSUE THREAD

**Issue by koiava** [mmp/pbrt-v3#87]
I tried to render Bathroom scene with pt and bdpt and got big difference on floor and on Foam.
[pt bathroom](https://goo.gl/photos/LHBRydQt6P6XxH389)
[bdpt bathroom](https://goo.gl/photos/Fw8haBXkzH1cvE9G9)
Then I investigated that issue and findout that bump mapping is broken.
I don't know which one should I take as a reference because both of them look wrong.
[pt](https://goo.gl/photos/bGbkvU9jSH6YXkTA8)
[bdpt](https://goo.gl/photos/bEBVeVJjjwpjwJp66)
You can download simple reproducer from [here](https://drive.google.com/open?id=0B1BdXfSJmkVYRldVSzM3aVpnazQ).

**Comment by mmp** [comment]
(This could be related to issue #73)

**Comment by wjakob** [comment]
Should be fixed by #94

**Comment by mmp** [comment]
There's actually another issue here related to bump mapping for rays that start from lights. (Have to run now, will push a commit and update this evening.)

**Comment by mmp** [comment]
This was an interesting bug--thanks for reporting it, and sorry it took so long to chase it down.

With the fix just pushed, results are more consistent, but not completely so. Part of the challenge is that the bump map magnitude in this scene is quite large. In turn, there is still a fundamental inconsistency between the scene as seen from paths from the camera and paths from the light that I don't think there's anything to be done about.

If the bump magnitude is scaled down as in the attached scene, then results are pretty close between the two approaches.
[scene.pbrt.txt](https://github.com/mmp/pbrt-v3/files/601559/scene.pbrt.txt)
