### ISSUE TITLE
lens specification for realistic camera 

### ISSUE THREAD

**Issue by jeko00** [mmp/pbrt-v3#91]
Hi all,
I was trying to use my own objective spec file with the realistic camera model. 
How do specify a planar surface (radius->∞)? Do I just use a "large" radius and if 
so what would be a "large" radius.

Thanks in advanced - regards Jens Kowal

**Comment by mmp** [comment]
Support for planar lens elements isn't currently implemented (except for the aperture stop, which is sort of a special case). If using a very large radius isn't sufficient for your needs, you'd have to modify the code to add support for that.
